# File: _decoder_.py
# Code: Claude Code and Codex
# Review: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

import os
import pickle
import platform

from ._asset_ import AssetManager
from ._mesh_ import MeshManager
from ._plot_ import PlotManager
from ._scene_ import FixedScene, Scene
from ._session_ import FixedSession, Session
from ._utils_ import Utils


class BlenderApp:
    """Attach to a project exported by the Blender addon and build a runnable session.

    The addon writes ``data.pickle`` and ``param.pickle`` into a
    per-project directory under ``~/.local/share/ppf-cts/git-<branch>/<name>/``.
    :meth:`open` is the canonical entry point: it decodes those pickles,
    populates the scene, applies parameters, and builds a
    ``FixedSession`` accessible via :attr:`scene` and :attr:`session`.

    Example:
        Canonical notebook cell (as generated by the Blender addon),
        attach to a transferred project and run it::

            from frontend import BlenderApp

            app = BlenderApp.open("rod-example-3")
            app.scene.report()
            app.scene.preview()
            app.session.run()
            app.session.preview()
    """

    def __init__(self, name: str, verbose: bool = False, progress_callback=None):
        """Initialize the BlenderApp.

        Args:
            name (str): The name of the Blender project.
            verbose (bool): Enable verbose logging.
            progress_callback: Optional callable ``fn(progress: float, info: str)`` invoked during long-running operations. ``progress`` is in ``[0.0, 1.0]``.
        """
        self._verbose = verbose
        self._name = name
        self._progress_callback = progress_callback

        # Get current git branch name for directory structure
        import subprocess

        # First try to read from .git/branch_name.txt
        git_branch = "unknown"
        try:
            branch_file = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "..",
                ".git",
                "branch_name.txt"
            )
            if os.path.exists(branch_file):
                with open(branch_file) as f:
                    git_branch = f.read().strip()
                    if not git_branch:
                        git_branch = "unknown"
        except Exception:
            pass

        # Fallback to git command if branch_name.txt not found or empty
        if git_branch == "unknown":
            try:
                git_branch = subprocess.check_output(
                    ["git", "branch", "--show-current"],
                    cwd=os.path.dirname(os.path.abspath(__file__)),
                    text=True,
                    stderr=subprocess.DEVNULL,
                ).strip()
                if not git_branch:
                    git_branch = "unknown"
            except Exception as _:
                git_branch = "unknown"

        # Windows native bundles must stay self-contained; mirrors
        # _app_.py:get_data_dirpath and server.py:make_root.
        if platform.system() == "Windows":
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            self._data_dirpath = os.path.join(
                base_dir, "local", "share", "ppf-cts", f"git-{git_branch}"
            )
        else:
            self._data_dirpath = os.path.join(
                os.path.expanduser("~"),
                ".local",
                "share",
                "ppf-cts",
                f"git-{git_branch}",
            )
        self._root = os.path.join(
            self._data_dirpath,
            self._name,
        )
        cache_root = os.path.join(self._root, ".cash")
        os.makedirs(cache_root, exist_ok=True)
        self._asset_manager = AssetManager()
        self._mesh_manager = MeshManager(cache_root)
        self._scene = None
        self._session = None
        self._fixed_scene = None
        self._fixed_session = None

    def __getstate__(self):
        state = self.__dict__.copy()
        state["_progress_callback"] = None
        return state

    def _report_progress(self, progress: float, info: str):
        if self._progress_callback is not None:
            self._progress_callback(progress, info)

    @classmethod
    def open(
        cls,
        name: str,
        verbose: bool = False,
        progress_callback=None,
    ) -> "BlenderApp":
        """Open a Blender project and build its scene and session.

        Behavior:

        1. If the Blender addon has uploaded both ``data.pickle`` and
           ``param.pickle`` under the project root, ``populate().make()``
           is invoked to build a fresh scene and session in this process.
        2. Otherwise, ``FileNotFoundError`` is raised — the user must
           click "Transfer" in the Blender addon first.

        After ``open()``, ``app.scene`` and ``app.session`` are the built
        ``FixedScene`` / ``FixedSession`` objects, ready for report,
        preview, run, and stream.

        Example:
            Notebook cell generated by the Blender addon — attach to the
            transferred project and run it::

                from frontend import BlenderApp

                app = BlenderApp.open("<project>")
                app.scene.preview()
                app.session.run()
                app.session.preview()
        """
        app = cls(name, verbose=verbose, progress_callback=progress_callback)
        data_path = os.path.join(app._root, "data.pickle")
        param_path = os.path.join(app._root, "param.pickle")
        if not (os.path.exists(data_path) and os.path.exists(param_path)):
            raise FileNotFoundError(
                f"Blender has not uploaded project '{name}' to {app._root}. "
                f"In the Blender addon, click 'Transfer' first."
            )
        # Invariant: whenever data.pickle and param.pickle both exist,
        # upload_id.txt must also exist. It's stamped by the Blender
        # addon's upload handler at write time and is the identity that
        # client build-tracking pins against. If it's missing, the
        # project predates upload_id tracking (or someone wrote pickles
        # out-of-band); refuse to build and tell the user how to migrate.
        upload_id_path = os.path.join(app._root, "upload_id.txt")
        if not os.path.exists(upload_id_path):
            raise FileNotFoundError(
                f"Project '{name}' at {app._root} has data.pickle and "
                f"param.pickle but no upload_id.txt. This project predates "
                f"upload_id tracking. Re-upload from the Blender addon, "
                f"or run `python tools/backfill_upload_ids.py` to stamp a "
                f"fresh id on every legacy project."
            )
        app.populate().make()
        return app


    def populate(self) -> "BlenderApp":
        """Populate the scene with objects decoded from ``data.pickle``.

        Also peeks at ``param.pickle`` for per-group fTetWild overrides so
        that tetrahedralization can use them at build time; full
        parameter application is deferred to :meth:`make`.

        Example:
            Two-stage construction (useful when you want to inspect the
            mutable scene before parameters are applied)::

                from frontend import BlenderApp

                app = BlenderApp("my-project")
                app.populate()
                app.make()
                app.session.run()
        """
        data_path = os.path.join(self._root, "data.pickle")
        assert os.path.exists(data_path)

        self._report_progress(0.05, "Loading scene data...")
        self._asset_manager = AssetManager()
        self._scene = Scene("scene", PlotManager(), self._asset_manager)
        self._scene_decoder = SceneDecoder(
            data_path,
            self._asset_manager,
            self._mesh_manager,
        )
        # Peek at param.pickle for per-group fTetWild overrides so
        # populate_objects can pass them into tetrahedralize() at build
        # time. The full param.pickle is applied later in make(). Fan the
        # group-level kwargs dict out to every UUID in the group.
        ftetwild_by_uuid: dict = {}
        param_path = os.path.join(self._root, "param.pickle")
        if os.path.exists(param_path):
            with open(param_path, "rb") as _pf:
                _pdata = pickle.load(_pf)
            for _ge in _pdata.get("group", []):
                if len(_ge) < 3:
                    continue
                _gp, _, _uuids = _ge[0], _ge[1], _ge[2]
                _kw = (_gp or {}).get("ftetwild") or {}
                if not _kw:
                    continue
                for _uuid in _uuids:
                    if _uuid:
                        ftetwild_by_uuid[_uuid] = _kw
        self._scene_decoder.populate_objects(
            self._scene,
            verbose=self._verbose,
            progress_callback=lambda progress, info: self._report_progress(
                0.10 + 0.50 * progress,
                info,
            ),
            ftetwild_by_uuid=ftetwild_by_uuid,
        )
        return self

    def make(self) -> "BlenderApp":
        """Apply ``param.pickle`` to the populated scene and build a runnable session.

        Applies per-object parameters, pin configuration, cross-stitch
        constraints, explicit merge pairs, and invisible colliders to the
        scene, then builds the fixed scene and session. The resulting
        state is persisted to ``app_state.pickle`` on a best-effort basis.

        Example:
            Finish the build after :meth:`populate`, then run the session::

                from frontend import BlenderApp

                app = BlenderApp("my-project").populate().make()
                app.session.run()
                app.session.preview()
        """
        assert self._scene is not None, "Scene must be populated before making the app"
        param_path = os.path.join(self._root, "param.pickle")
        assert os.path.exists(param_path)

        self._report_progress(0.65, "Applying object parameters...")
        param_decoder = ParamDecoder().set_path(param_path)
        param_decoder.apply_to_objects(self._scene, verbose=self._verbose)
        self._report_progress(0.72, "Applying pin configuration...")
        param_decoder.apply_pin_config(self._scene, verbose=self._verbose)
        if param_decoder.cross_stitch:
            self._report_progress(0.78, "Applying cross-stitch constraints...")
            for entry in param_decoder.cross_stitch:
                self._apply_explicit_cross_stitch(entry, verbose=self._verbose)
        if param_decoder.explicit_merge_pairs:
            self._scene.set_explicit_merge_pairs(param_decoder.explicit_merge_pairs)
        self._report_progress(0.82, "Applying invisible colliders...")
        param_decoder.apply_invisible_colliders(self._scene, verbose=self._verbose)
        self._report_progress(0.84, "Building scene: preparing objects...")
        self._fixed_scene = self._scene.build(
            progress_callback=lambda progress, info: self._report_progress(
                0.84 + 0.10 * progress,
                info,
            )
        )
        self._report_progress(0.94, "Initializing session...")
        self._session = Session(
            self._name,
            self._root,
            os.path.dirname(os.path.dirname(__file__)),
            self._data_dirpath,
            "session",
        ).init(self._fixed_scene)
        self._report_progress(0.97, "Applying session parameters...")
        param_decoder.apply_to_session(self._session, verbose=self._verbose)
        self._fixed_session = self._session.build()
        self._persist_app_state()
        self._report_progress(0.97, "Build decode complete.")
        return self

    def _persist_app_state(self) -> None:
        """Write this BlenderApp to ``{_root}/app_state.pickle`` so that
        both the Blender-addon server and future notebook runs can
        discover the built state. The Blender-addon server reads it back
        through ``server/engine.py:AppState.load`` when it needs to adopt
        an externally-built session.

        Raises any persistence error (disk full, permission denied,
        pickling failure) rather than silently swallowing it: a failed
        persist means the server-side state machine won't pick up this
        build, and the caller should know.
        """
        # _process holds a subprocess Popen with non-picklable locks.
        if self._fixed_session is not None:
            self._fixed_session._process = None
        path = os.path.join(self._root, "app_state.pickle")
        os.makedirs(self._root, exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "wb") as f:
            pickle.dump(self, f)
        os.replace(tmp, path)

    def _apply_explicit_cross_stitch(self, entry, verbose=False):
        import numpy as np

        source_name = entry.get("source_uuid", "")
        target_name = entry.get("target_uuid", "")
        if not source_name or not target_name:
            raise ValueError("Cross-stitch entry missing source_uuid/target_uuid")

        obj_info = self._scene_decoder._object_info
        source_info = obj_info.get(source_name)
        target_info = obj_info.get(target_name)
        if source_info is None or target_info is None:
            raise ValueError(
                f"Cross-stitch references unknown object: "
                f"source={source_name!r} target={target_name!r}"
            )

        ind = np.array(entry.get("ind", []), dtype=np.int64)
        w = np.array(entry.get("w", []), dtype=np.float32)
        if len(ind) == 0 or len(w) == 0:
            return

        if target_info.get("type") == "SOLID":
            target_points = entry.get("target_points", [])
            if len(target_points) != len(ind):
                return
            # target_info["V"] is already in world space (transform applied
            # during populate_objects), so use it directly — do NOT apply the
            # object transform again.
            target_pos = np.asarray(target_info["V"], dtype=np.float64)
            target_face = target_info["F"]
            stitch_ind = []
            stitch_w = []
            # Pre-compute per-face geometric data for vectorized projection
            _fv = np.asarray(target_face)  # (F, 3)
            _p0 = target_pos[_fv[:, 0]]  # (F, 3)
            _p1 = target_pos[_fv[:, 1]]  # (F, 3)
            _p2 = target_pos[_fv[:, 2]]  # (F, 3)
            _e1 = _p1 - _p0  # (F, 3)
            _e2 = _p2 - _p0  # (F, 3)
            _d00 = np.sum(_e1 * _e1, axis=1)  # (F,)
            _d01 = np.sum(_e1 * _e2, axis=1)  # (F,)
            _d11 = np.sum(_e2 * _e2, axis=1)  # (F,)
            _denom = _d00 * _d11 - _d01 * _d01  # (F,)
            _valid = np.abs(_denom) > 1e-20  # (F,)
            _safe_denom = np.where(_valid, _denom, 1.0)  # avoid div-by-zero
            for src_row, anchor in zip(ind, target_points, strict=False):
                sv = np.array(anchor, dtype=np.float64)
                v0 = sv - _p0  # (F, 3)
                d20 = np.sum(v0 * _e1, axis=1)  # (F,)
                d21 = np.sum(v0 * _e2, axis=1)  # (F,)
                beta = np.where(_valid, (_d11 * d20 - _d01 * d21) / _safe_denom, -1.0)
                gamma = np.where(_valid, (_d00 * d21 - _d01 * d20) / _safe_denom, -1.0)
                alpha = 1.0 - beta - gamma
                alpha_c = np.clip(alpha, 0.0, 1.0)
                beta_c = np.clip(beta, 0.0, 1.0)
                gamma_c = np.clip(gamma, 0.0, 1.0)
                s = alpha_c + beta_c + gamma_c
                safe_s = np.where(s > 0, s, 1.0)
                alpha_c /= safe_s
                beta_c /= safe_s
                gamma_c /= safe_s
                proj = alpha_c[:, None] * _p0 + beta_c[:, None] * _p1 + gamma_c[:, None] * _p2
                dists = np.linalg.norm(sv - proj, axis=1)
                dists = np.where(_valid, dists, np.inf)
                best_fi = int(np.argmin(dists))
                if dists[best_fi] == np.inf:
                    continue
                best_bary = (float(alpha_c[best_fi]), float(beta_c[best_fi]), float(gamma_c[best_fi]))
                fv_best = target_face[best_fi]
                stitch_ind.append([int(src_row[0]), int(fv_best[0]), int(fv_best[1]), int(fv_best[2])])
                stitch_w.append([1.0, best_bary[0], best_bary[1], best_bary[2]])
            if not stitch_ind:
                return
            ind = np.array(stitch_ind, dtype=np.int64)
            w = np.array(stitch_w, dtype=np.float32)

        self._scene._cross_stitch.append({
            "source_name": source_name,
            "target_name": target_name,
            "ind": ind,
            "w": w,
            "stitch_stiffness": float(entry.get("stitch_stiffness", 1.0)),
        })
        if verbose:
            print(f"  Stitch {source_name} -> {target_name}: {len(ind)} edges (explicit)")

    @property
    def scene(self) -> FixedScene:
        """The built fixed scene — use this for ``.report()``,
        ``.preview()``, etc. The mutable pre-build ``Scene`` remains
        accessible as ``_scene`` for advanced callers.

        Example:
            Open a Blender-authored project and inspect the built scene::

                from frontend import BlenderApp

                app = BlenderApp.open("rod-example-3")
                app.scene.report()
                app.scene.preview()
        """
        assert self._fixed_scene is not None, (
            "Scene is not built yet. Call BlenderApp.open() or "
            ".populate().make() first."
        )
        return self._fixed_scene

    @property
    def session(self) -> FixedSession:
        """The built fixed session — use this for ``.run()``,
        ``.preview()``, ``.stream()``, etc.

        Example:
            Run a Blender-authored session and stream live output::

                from frontend import BlenderApp

                app = BlenderApp.open("rod-example-3")
                app.session.run()
                app.session.preview()
                app.session.stream()
        """
        assert self._fixed_session is not None, (
            "Session is not built yet. Call BlenderApp.open() or "
            ".populate().make() first."
        )
        return self._fixed_session


class ParamDecoder:
    """Load and apply ``param.pickle`` written by the Blender addon.

    Parameters are split across object-level (velocity, fTetWild hints,
    per-key ``param.set`` values), pin configuration, cross-stitch
    constraints, explicit merge pairs, invisible walls / spheres, and
    session-level scene settings. :meth:`set_path` loads the pickle,
    then the ``apply_*`` methods dispatch each section.

    Example:
        Apply a pickle to an existing scene and session (this is what
        :meth:`BlenderApp.make` does internally)::

            from frontend._decoder_ import ParamDecoder

            decoder = ParamDecoder().set_path("/path/to/param.pickle")
            decoder.apply_to_objects(scene)
            decoder.apply_pin_config(scene)
            decoder.apply_invisible_colliders(scene)
            fixed_scene = scene.build()
            decoder.apply_to_session(session)
    """

    def __init__(self):
        self._data = None

    def set_path(self, filepath: str) -> "ParamDecoder":
        """Load parameter data from a pickle file and cache it on this decoder.

        Args:
            filepath (str): Path to the pickle file. Must end in ``.pickle``.

        Returns:
            ParamDecoder: ``self`` for chaining.

        Example:
            Chain the load with a subsequent apply call::

                from frontend._decoder_ import ParamDecoder

                decoder = ParamDecoder().set_path("/path/to/param.pickle")
                decoder.apply_to_objects(scene)
        """
        assert filepath.endswith(".pickle"), "File must be a pickle file."
        with open(filepath, "rb") as f:
            self._data = pickle.load(f)
        assert "group" in self._data, "Group parameters not found in the data."
        assert "scene" in self._data, "Scene parameters not found in the data."
        self._pin_config = self._data.get("pin_config", {})
        self._explicit_merge_pairs = self._data.get("explicit_merge_pairs", [])
        self._cross_stitch = self._data.get("cross_stitch", [])
        return self

    @property
    def explicit_merge_pairs(self) -> list:
        return self._explicit_merge_pairs

    @property
    def cross_stitch(self) -> list:
        return self._cross_stitch

    def apply_to_objects(self, scene: Scene, verbose: bool = False):
        """Apply the loaded parameter data to the objects in ``scene``.

        Call :meth:`set_path` first. Per-object dicts (velocity,
        velocity-schedule, collision-windows) are keyed by UUID; other
        keys are forwarded to ``obj.param.set``. fTetWild overrides are
        consumed at populate-time and skipped here.

        Args:
            scene (Scene): The scene to which the parameters will be applied.
            verbose (bool): Enable verbose logging.

        Example:
            Load a pickle and apply per-object parameters to a populated scene::

                from frontend._decoder_ import ParamDecoder

                decoder = ParamDecoder().set_path("/path/to/param.pickle")
                decoder.apply_to_objects(scene, verbose=True)
        """
        assert self._data is not None, "Parameter data not set. Call set_path() first."
        if verbose:
            print("=== Object Parameters ===")
        for group_entry in self._data["group"]:
            params, objects = group_entry[0], group_entry[1]
            # Third tuple slot holds UUIDs aligned with ``objects``.
            # Per-object dicts (velocity / velocity-schedule / collision-
            # windows) are keyed on UUID by the encoder.
            if len(group_entry) <= 2:
                raise ValueError(
                    "Parameter group missing UUID list (third element); "
                    "re-export from Blender with current addon"
                )
            obj_uuids = group_entry[2]
            for obj_name, obj_uuid in zip(objects, obj_uuids):
                if not obj_uuid:
                    raise ValueError(
                        f"Object '{obj_name}' has empty UUID in parameter data"
                    )
                if verbose:
                    print(f"*** name: {obj_name} (uuid={obj_uuid}) ***")
                obj = scene.select(obj_uuid)
                obj.param.clear_all()
                for key, val in params.items():
                    if verbose:
                        print(f"  {key}: {val}")
                    if key == "velocity":
                        if isinstance(val, dict):
                            v = val.get(obj_uuid) if obj_uuid else None
                            if v is not None:
                                obj.velocity(*v)
                        else:
                            obj.velocity(*val)
                    elif key == "velocity-schedule":
                        if isinstance(val, dict):
                            s = val.get(obj_uuid) if obj_uuid else None
                            if s:
                                obj.velocity_schedule(s)
                        else:
                            obj.velocity_schedule(val)
                    elif key == "collision-windows":
                        if isinstance(val, dict):
                            w = val.get(obj_uuid) if obj_uuid else None
                            if w:
                                obj.collision_windows(w)
                    elif key == "ftetwild":
                        # Consumed at populate-time via the param.pickle peek;
                        # no per-object ParamHolder slot by design (would
                        # break concat_tet_param / concat_tri_param key-set
                        # equality in _scene_.extend_param).
                        pass
                    else:
                        obj.param.set(key, val)

    def apply_to_session(self, session: Session, verbose: bool = False):
        """Apply scene-level and dynamic parameters from the loaded data to ``session``.

        Call :meth:`set_path` first. Static scene parameters are forwarded to
        ``session.param.set``; ``inactive-momentum`` is additionally set as a
        dynamic hold. Dynamic parameter keyframes from ``dyn_param`` are
        applied via ``session.param.dyn(...)``.

        Args:
            session (Session): The session to which the parameters will be applied.
            verbose (bool): Enable verbose logging.

        Example:
            Apply scene-level and dynamic parameters to a freshly initialized session::

                from frontend._decoder_ import ParamDecoder

                decoder = ParamDecoder().set_path("/path/to/param.pickle")
                session = app.session.create(scene).init(fixed_scene)
                decoder.apply_to_session(session)
                session.build().start()
        """
        assert self._data is not None, "Parameter data not set. Call set_path() first."
        if verbose:
            print("=== Session Parameters ===")
        session.param.clear_all()

        for k, v in self._data["scene"].items():
            if verbose:
                print(f"  {k}: {v}")
            if k == "inactive-momentum" and v > 0:
                inactive_momentum_time = float(v)
                session.param.set("inactive-momentum")
                session.param.dyn("inactive-momentum").time(inactive_momentum_time).hold().change(False)
            else:
                session.param.set(k, v)

        # Apply dynamic parameters if present
        dyn_param = self._data.get("dyn_param", {})
        for key, entries in dyn_param.items():
            if len(entries) < 2:
                continue
            if verbose:
                print(f"  dyn({key}): {len(entries)} keyframes")
            # First entry is initial value (already set via static params above).
            # Subsequent entries are (time, value, is_hold) tuples.
            builder = session.param.dyn(key)
            for entry in entries[1:]:
                t, v = entry[0], entry[1]
                is_hold = entry[2] if len(entry) > 2 else False
                if is_hold:
                    builder.time(t).hold()
                else:
                    if isinstance(v, list) and len(v) == 1:
                        builder.time(t).change(v[0])
                    else:
                        builder.time(t).change(v)

    def apply_pin_config(self, scene, verbose: bool = False):
        """Apply saved pin configuration to scene pin holders.

        Applies unpin time, pull strength, pin group id, embedded move
        keyframes, and explicit pin operations (spin / scale / move_by /
        torque) to each pin holder that has a matching config entry.
        Call after the scene is populated and pins are created.

        Example:
            Reapply pin settings after populating objects::

                from frontend._decoder_ import ParamDecoder

                decoder = ParamDecoder().set_path("/path/to/param.pickle")
                decoder.apply_to_objects(scene)
                decoder.apply_pin_config(scene, verbose=True)
        """
        if not self._pin_config:
            return
        if verbose:
            print("=== Pin Config ===")
        for dyn_name, dyn_obj in scene.object_dict.items():
            # pin_config keyed by UUID; objects are registered by UUID
            obj_cfg = self._pin_config.get(dyn_name, {})
            if not obj_cfg:
                continue
            for pin_holder in dyn_obj.pin_list:
                # For solid objects, use stored Blender indices for config lookup
                lookup_indices = getattr(pin_holder._data, '_blender_pin_indices', None) or pin_holder.index
                for vi in lookup_indices:
                    cfg = obj_cfg.get(vi)
                    if cfg is not None:
                        if "unpin_time" in cfg:
                            pin_holder.unpin(cfg["unpin_time"])
                            if verbose:
                                print(f"  {dyn_name}[{vi}]: unpin_time={cfg['unpin_time']}")
                        if "pull_strength" in cfg:
                            pin_holder.pull(cfg["pull_strength"])
                        if "pin_group_id" in cfg:
                            pin_holder._data.pin_group_id = cfg["pin_group_id"]
                            if verbose:
                                print(f"  {dyn_name}[{vi}]: pin_group_id={cfg['pin_group_id']}")
                        if "operations" in cfg or "pin_anim" in cfg:
                            import numpy as np
                            # Build embedded move ops for THIS pin's lookup vertex.
                            # Deltas are broadcast to all sim vertices in the pin.
                            pin_anim = cfg.get("pin_anim", {})
                            n_pin_verts = len(pin_holder.index)
                            keyframe = pin_anim.get(vi)
                            embedded_ops = []
                            if keyframe and len(keyframe["time"]) >= 2:
                                times = keyframe["time"]
                                positions = keyframe["position"]
                                from ._scene_ import MoveByOperation
                                prev_pos = np.array(positions[0])
                                prev_t = times[0]
                                for t, pos in zip(times[1:], positions[1:]):
                                    d = np.array(pos) - prev_pos
                                    delta = np.tile(d, (n_pin_verts, 1))
                                    embedded_ops.append(MoveByOperation(
                                        delta=delta,
                                        t_start=prev_t,
                                        t_end=t,
                                        transition="linear",
                                    ))
                                    prev_pos = np.array(pos)
                                    prev_t = t
                            embedded_move_index = cfg.get("embedded_move_index", -1)
                            explicit_operations = cfg.get("operations", [])
                            # Validate: torque cannot be mixed with kinematic ops
                            op_types = {o.get("type") for o in explicit_operations}
                            if "torque" in op_types and op_types & {"spin", "scale", "move_by"}:
                                raise ValueError(
                                    f"Pin on '{dyn_name}': "
                                    "torque cannot be mixed with move/spin/scale operations"
                                )
                            # Clear existing operations
                            pin_holder._data.operations = []
                            # Re-add in the correct order
                            explicit_idx = 0
                            embedded_inserted = False
                            total = len(explicit_operations) + (1 if embedded_move_index >= 0 else 0)
                            if total == 0 and embedded_ops:
                                # Only embedded move, no explicit ops
                                pin_holder._data.operations.extend(embedded_ops)
                                embedded_inserted = True
                            for pos in range(total):
                                if pos == embedded_move_index and not embedded_inserted:
                                    # Insert embedded move operations at this position
                                    pin_holder._data.operations.extend(embedded_ops)
                                    embedded_inserted = True
                                else:
                                    if explicit_idx < len(explicit_operations):
                                        op = explicit_operations[explicit_idx]
                                        explicit_idx += 1
                                        t_start = op.get("t_start", 0)
                                        t_end = op.get("t_end", 1)
                                        transition = op.get("transition", "linear")
                                        if transition != "linear":
                                            pin_holder.interp(transition)
                                        if op["type"] == "spin":
                                            center_mode = op.get("center_mode", "absolute")
                                            pin_holder.spin(
                                                center=op.get("center"),
                                                axis=op.get("axis", [0, 1, 0]),
                                                angular_velocity=op.get("angular_velocity", 360),
                                                t_start=t_start,
                                                t_end=t_end,
                                                center_mode=center_mode,
                                            )
                                        elif op["type"] == "scale":
                                            center_mode = op.get("center_mode", "absolute")
                                            pin_holder.scale(
                                                op.get("factor", 1.0),
                                                t_start=t_start,
                                                t_end=t_end,
                                                center=op.get("center"),
                                                center_mode=center_mode,
                                            )
                                        elif op["type"] == "move_by":
                                            pin_holder.move_by(
                                                op.get("delta", [0, 0, 0]),
                                                t_start=t_start,
                                                t_end=t_end,
                                            )
                                        elif op["type"] == "torque":
                                            blender_hint = int(op.get("hint_vertex", -1))
                                            # Translate Blender hint vertex to nearest tet vertex by position
                                            # (robust to re-tetrahedralization)
                                            tet_V = getattr(pin_holder._data, '_tet_V', None)
                                            blender_vert = getattr(pin_holder._data, '_blender_vert', None)
                                            if tet_V is not None and blender_vert is not None and blender_hint >= 0:
                                                import numpy as _np
                                                hint_pos = blender_vert[blender_hint]
                                                dists = _np.sum((tet_V - hint_pos)**2, axis=1)
                                                sim_hint = int(_np.argmin(dists))
                                            else:
                                                sim_hint = blender_hint
                                            pin_holder.torque(
                                                magnitude=op.get("magnitude", 1.0),
                                                axis_component=int(op.get("axis_component", 2)),
                                                hint_vertex=sim_hint,
                                                t_start=t_start,
                                                t_end=t_end,
                                            )
                                        if transition != "linear":
                                            pin_holder.interp("linear")
                            # If embedded move wasn't inserted yet (index beyond end), append
                            if not embedded_inserted and embedded_move_index >= 0:
                                pin_holder._data.operations.extend(embedded_ops)
                            if verbose:
                                print(f"  {dyn_name}[{vi}]: operations={len(pin_holder.operations)}")
                        break

    def apply_invisible_colliders(self, scene, verbose: bool = False):
        """Create invisible wall and sphere colliders on the scene from the loaded pickle data.

        Must be called BEFORE ``scene.build()``.

        Example:
            Add the pickle's invisible walls and spheres just before building::

                from frontend._decoder_ import ParamDecoder

                decoder = ParamDecoder().set_path("/path/to/param.pickle")
                decoder.apply_invisible_colliders(scene)
                fixed_scene = scene.build()
        """
        ic = self._data.get("invisible_colliders", {})
        if not ic:
            return
        if verbose:
            print("=== Invisible Colliders ===")
        for w in ic.get("walls", []):
            wall = scene.add.invisible.wall(w["position"], w["normal"])
            wall.param.set("contact-gap", w.get("contact_gap", 1e-3))
            wall.param.set("friction", w.get("friction", 0.0))
            wall.param.set("active-duration", w.get("active_duration", -1.0))
            thickness = float(w.get("thickness", 1.0))
            assert thickness > 0.0, (
                f"invisible wall thickness must be > 0 (got {thickness})"
            )
            wall.param.set("thickness", thickness)
            keyframes = w.get("keyframes", [])
            for kf in keyframes[1:]:
                wall.move_to(kf["position"], kf["time"])
            if verbose:
                print(f"  Wall: pos={w['position']}, normal={w['normal']}, kf={len(keyframes)}")
        for s in ic.get("spheres", []):
            sphere = scene.add.invisible.sphere(s["position"], s["radius"])
            if s.get("hemisphere", False):
                sphere.hemisphere()
            if s.get("invert", False):
                sphere.invert()
            sphere.param.set("contact-gap", s.get("contact_gap", 1e-3))
            sphere.param.set("friction", s.get("friction", 0.0))
            sphere.param.set("active-duration", s.get("active_duration", -1.0))
            thickness = float(s.get("thickness", 1.0))
            assert thickness > 0.0, (
                f"invisible sphere thickness must be > 0 (got {thickness})"
            )
            sphere.param.set("thickness", thickness)
            keyframes = s.get("keyframes", [])
            for kf in keyframes[1:]:
                sphere.transform_to(kf["position"], kf["radius"], kf["time"])
            if verbose:
                print(f"  Sphere: pos={s['position']}, r={s['radius']}, inv={s.get('invert')}, hemi={s.get('hemisphere')}, kf={len(keyframes)}")


class SceneDecoder:
    """Decode ``data.pickle`` written by the Blender addon into scene objects.

    Handles canonical mesh deduplication, per-instance transforms, cached
    tetrahedralization for SOLID groups, pin registration with
    Blender-to-sim surface mapping, UV assignment for SHELL groups, and
    rod / static groups. Used internally by :class:`BlenderApp`.

    Example:
        Drive the decoder directly to populate a scene (this is what
        :meth:`BlenderApp.populate` does internally)::

            from frontend._asset_ import AssetManager
            from frontend._mesh_ import MeshManager
            from frontend._decoder_ import SceneDecoder

            assets = AssetManager()
            meshes = MeshManager("/tmp/cache")
            decoder = SceneDecoder("/path/to/data.pickle", assets, meshes)
            decoder.populate_objects(scene, verbose=True)
    """

    def __init__(
        self, filepath: str, asset_manager: AssetManager, mesh_manager: MeshManager
    ):
        assert filepath.endswith(".pickle"), "File must be a pickle file."
        with open(filepath, "rb") as f:
            self._data = pickle.load(f)
        self._asset = asset_manager
        self._mesh = mesh_manager
        self._object_info = {}  # name → {type, vert, V, F} for stitch generation

    def _tetra_cache_path(self, tri_mesh) -> str:
        return tri_mesh.compute_cache_path(f"{tri_mesh.hash}_tetrahedralize_.npz")

    def _summarize_tetra_jobs(self, tetra_jobs: list[dict]) -> str:
        if not tetra_jobs:
            return "no solid tetrahedralizations"
        labels = [
            f"{job['name']} ({'cached' if job['cached'] else 'new'})"
            for job in tetra_jobs
        ]
        if len(labels) > 5:
            return (
                f"{len(labels)} tetrahedralizations: "
                f"{', '.join(labels[:5])}, +{len(labels) - 5} more"
            )
        return f"{len(labels)} tetrahedralizations: {', '.join(labels)}"

    @staticmethod
    def _apply_transform(local_vert, transform):
        """Apply a 4x4 transform to local-space vertices and return world-space vertices as float32."""
        import numpy as np
        mat = np.asarray(transform, dtype=np.float64)
        v = np.asarray(local_vert, dtype=np.float64)
        return (v @ mat[:3, :3].T + mat[:3, 3]).astype(np.float32)

    def populate_objects(self, scene: Scene, verbose: bool = False, progress_callback=None, ftetwild_by_uuid: dict | None = None) -> Scene:
        """Populate ``scene`` with objects from the decoder's pickle data.

        Handles STATIC, SOLID, SHELL, and ROD groups, including canonical
        mesh deduplication by UUID, per-instance transforms, cached
        tetrahedralization (with per-UUID fTetWild overrides), pin
        registration with Blender-to-sim surface mapping, and stitches.

        Args:
            scene (Scene): The scene to populate.
            verbose (bool): Enable verbose logging.
            progress_callback: Optional callable ``fn(progress: float, info: str)`` invoked during loading. ``progress`` is in ``[0.0, 1.0]``.
            ftetwild_by_uuid (dict | None): Optional mapping of object UUID to fTetWild keyword arguments used during tetrahedralization.

        Returns:
            Scene: The populated scene.

        Example:
            Populate a fresh scene from a Blender pickle::

                from frontend._asset_ import AssetManager
                from frontend._mesh_ import MeshManager
                from frontend._decoder_ import SceneDecoder

                decoder = SceneDecoder(
                    "/path/to/data.pickle", AssetManager(), MeshManager("/tmp/cache"),
                )
                decoder.populate_objects(scene, verbose=True)
                fixed_scene = scene.build()
        """
        planning_steps = sum(len(group.get("object", [])) for group in self._data)
        planning_weight = max(1.0, 0.35 * planning_steps)
        object_entries = []
        tetra_jobs = []
        object_work = 0.0
        completed_work = 0.0

        # Mesh deduplication: canonical mesh data keyed by name
        canonical_meshes = {}  # name -> {"vert": local_vert, "face": face, "uv": uv, "stitch": ...}

        def report(info: str, total_work_override: float | None = None):
            if progress_callback is not None:
                total = total_work if total_work_override is None else total_work_override
                progress_callback(
                    completed_work / total if total > 0 else 1.0,
                    info,
                )

        # First pass: resolve mesh_ref and build canonical mesh table
        # canonical_meshes is keyed by UUID (encoder sends mesh_ref as UUID)
        # Also keep asset_name (Blender name) for asset registration
        canonical_asset_name = {}  # uuid -> Blender name for asset registration
        for group in self._data:
            objects = group.get("object", None)
            assert objects is not None, "Object data not found in the group."
            for obj in objects:
                name = obj.get("name")
                if not name:
                    raise ValueError("Object missing required 'name' field")
                obj_uuid = obj.get("uuid", "")
                if not obj_uuid:
                    raise ValueError(f"Object '{name}' missing required 'uuid' field")
                if "mesh_ref" not in obj and "vert" in obj:
                    # Canonical mesh: store local data for referenced instances
                    canonical_meshes[obj_uuid] = {
                        "vert": obj.get("vert"),
                        "face": obj.get("face"),
                        "edge": obj.get("edge"),
                        "uv": obj.get("uv", None),
                        "stitch": obj.get("stitch", None),
                    }
                    canonical_asset_name[obj_uuid] = name

        planning_increment = planning_weight / planning_steps if planning_steps > 0 else 0.0
        report("Scanning build plan...", planning_weight)
        for group in self._data:
            objects = group.get("object", None)
            assert objects is not None, "Object data not found in the group."
            group_type = group.get("type")
            for obj in objects:
                name = obj.get("name")
                report(
                    f"Scanning build plan: {name}...",
                    planning_weight,
                )

                # Resolve mesh data: either from obj directly or via mesh_ref
                mesh_ref = obj.get("mesh_ref")
                transform = obj.get("transform")
                if mesh_ref is not None and mesh_ref not in canonical_meshes:
                    raise ValueError(
                        f"Object '{name}' has mesh_ref={mesh_ref!r} "
                        f"that does not match any canonical mesh UUID"
                    )
                if mesh_ref is not None and mesh_ref in canonical_meshes:
                    # Duplicate: get local mesh from canonical, apply transform
                    ref = canonical_meshes[mesh_ref]
                    local_vert = ref["vert"]
                    face = ref["face"]
                    vert = self._apply_transform(local_vert, transform) if transform is not None else local_vert
                    obj["_resolved_vert"] = vert
                    obj["_resolved_face"] = face
                    obj["_resolved_uv"] = ref.get("uv")
                    obj["_resolved_stitch"] = ref.get("stitch")
                    obj["_resolved_edge"] = ref.get("edge")
                    obj["_mesh_ref_resolved"] = mesh_ref
                elif transform is not None and "vert" in obj:
                    # Canonical with transform: apply transform to local vertices
                    vert = self._apply_transform(obj["vert"], transform)
                    obj["_resolved_vert"] = vert
                    obj["_resolved_face"] = obj.get("face")
                    obj["_resolved_uv"] = obj.get("uv")
                    obj["_resolved_stitch"] = obj.get("stitch")
                    obj["_resolved_edge"] = obj.get("edge")
                    obj["_mesh_ref_resolved"] = None
                else:
                    # Legacy format: vertices already in world space
                    obj["_resolved_vert"] = obj.get("vert")
                    obj["_resolved_face"] = obj.get("face")
                    obj["_resolved_uv"] = obj.get("uv")
                    obj["_resolved_stitch"] = obj.get("stitch")
                    obj["_resolved_edge"] = obj.get("edge")
                    obj["_mesh_ref_resolved"] = None

                entry = {
                    "group_type": group_type,
                    "obj": obj,
                    "name": name,
                    "base_weight": 1.0,
                    "tetra_weight": 0.0,
                    "tetra_index": None,
                    "tetra_cached": False,
                    "tri_mesh": None,
                }
                if group_type == "SOLID":
                    report(
                        f"Checking tetra cache: {name}...",
                        planning_weight,
                    )
                    # For dedup: use LOCAL vertices for tet (same hash for duplicates)
                    if mesh_ref and mesh_ref in canonical_meshes:
                        tet_vert = canonical_meshes[mesh_ref]["vert"]
                        tet_face = canonical_meshes[mesh_ref]["face"]
                    elif "vert" in obj and obj.get("transform") is not None:
                        tet_vert = obj["vert"]  # Local-space
                        tet_face = obj.get("face")
                    else:
                        tet_vert = obj["_resolved_vert"]  # Legacy: world-space
                        tet_face = obj["_resolved_face"]
                    tri_mesh = self._mesh.create.tri(tet_vert, tet_face)
                    cached = os.path.exists(self._tetra_cache_path(tri_mesh))
                    entry["tri_mesh"] = tri_mesh
                    entry["tetra_cached"] = cached
                    entry["tetra_index"] = len(tetra_jobs) + 1
                    entry["tetra_weight"] = 3.0 if cached else 8.0
                    object_work += entry["tetra_weight"]
                    tetra_jobs.append(
                        {
                            "name": entry["name"],
                            "cached": cached,
                        }
                    )
                object_entries.append(entry)
                object_work += entry["base_weight"]
                completed_work += planning_increment

        total_work = planning_weight + 0.5 + object_work
        # Deduplicate tet jobs: skip objects whose tri_mesh hash matches an
        # earlier object (they'll reuse the same tet result).
        tet_hash_seen = {}  # tri_mesh.hash -> entry index in object_entries
        for i, entry in enumerate(object_entries):
            if entry["group_type"] == "SOLID" and entry["tri_mesh"] is not None:
                h = entry["tri_mesh"].hash
                if h in tet_hash_seen:
                    # Mark as reusing an earlier tet result
                    entry["tetra_reuse_from"] = tet_hash_seen[h]
                    # Reclaim the weight we allocated
                    object_work -= entry["tetra_weight"]
                    entry["tetra_weight"] = 0.0
                else:
                    tet_hash_seen[h] = i
                    entry["tetra_reuse_from"] = None

        # Rebuild tetra_jobs list for accurate reporting
        tetra_jobs = []
        tetra_idx = 0
        for entry in object_entries:
            if entry["group_type"] == "SOLID" and entry["tri_mesh"] is not None:
                if entry.get("tetra_reuse_from") is None:
                    tetra_idx += 1
                    entry["tetra_index"] = tetra_idx
                    tetra_jobs.append({"name": entry["name"], "cached": entry["tetra_cached"]})
                else:
                    entry["tetra_index"] = None

        total_work = planning_weight + 0.5 + object_work
        report(f"Build plan: {self._summarize_tetra_jobs(tetra_jobs)}")
        completed_work += 0.5

        object_iter = iter(object_entries)

        for group in self._data:
            objects = group.get("object", None)
            assert objects is not None, "Object data not found in the group."
            group_type = group.get("type")
            if verbose:
                print(f"--- new group: {group_type} ---")
            for obj in objects:
                entry = next(object_iter)
                name = obj.get("name")
                if not name:
                    raise ValueError("Object missing required 'name' field")
                obj_uuid = obj.get("uuid", "")
                if not obj_uuid:
                    raise ValueError(f"Object '{name}' missing required 'uuid' field")
                mesh_ref = obj.get("_mesh_ref_resolved")
                transform = obj.get("transform")
                # Local-space mesh data (for asset registration)
                if mesh_ref and mesh_ref in canonical_meshes:
                    local_vert = canonical_meshes[mesh_ref]["vert"]
                    face = canonical_meshes[mesh_ref]["face"]
                    edge = canonical_meshes[mesh_ref].get("edge")
                    uv = canonical_meshes[mesh_ref].get("uv")
                elif "vert" in obj:
                    local_vert = obj["vert"]  # Local if transform present, world if legacy
                    face = obj.get("face")
                    edge = obj.get("edge")
                    uv = obj.get("uv", None)
                else:
                    raise ValueError(
                        f"Object '{name}' (uuid={obj_uuid}) has no mesh data "
                        f"and no valid mesh_ref"
                    )
                # World-space vertices (for object_info used by pin mapping etc.)
                vert = obj.get("_resolved_vert", local_vert)
                report(f"Loading {group_type}: {name}...")
                if verbose:
                    if edge is not None:
                        print(
                            f"  * name: {name}, vert: {vert.shape}, edge: {edge.shape}, uv: {len(uv) if uv is not None else 'None'}"
                        )
                    else:
                        print(
                            f"  * name: {name}, vert: {vert.shape}, face: {face.shape if face is not None else 'None'}, uv: {len(uv) if uv is not None else 'None'}"
                        )
                if group_type == "STATIC":
                    import numpy as np

                    transform_anim = obj.get("transform_animation", None)
                    static_ops = obj.get("static_ops", []) or []
                    if transform_anim is not None and static_ops:
                        raise ValueError(
                            f"STATIC object '{name}' has both transform_animation "
                            "and static_ops — encoder should have rejected this."
                        )
                    if verbose:
                        print(
                            f"      > transform_animation: "
                            f"{'YES' if transform_anim else 'NO'}, "
                            f"static_ops: {len(static_ops)}"
                        )

                    def _setup_pin_shell():
                        """Common setup for animated static objects: a
                        zero-stiffness shell whose vertices are driven by
                        pin operations. Returns the Object plus its
                        rest-frame translation (``(obj, rest_t)``).
                        """
                        self._asset.add.tri(name, local_vert, face)
                        _o = scene.add(name, obj_uuid)
                        if transform is not None:
                            _o.mat4x4(transform)
                        _o.param.set("density", 0.0)
                        _o.param.set("young-mod", 0.0)
                        _o.param.set("poiss-rat", 0.0)
                        _o.param.set("bend", 0.0)
                        # Mark for preview suppression: the shell's pins
                        # are implementation detail, not user-chosen.
                        _o._is_static_moving = True
                        rest_t = (
                            np.asarray(transform, dtype=np.float64)[:3, 3]
                            if transform is not None
                            else np.zeros(3, dtype=np.float64)
                        )
                        return _o, rest_t

                    if transform_anim is not None:
                        # Case 1: Blender keyframes drive the pose. Blender
                        # already animates the object in the viewport, so no
                        # PC2 playback is needed (exclude from output).
                        _obj, rest_translation = _setup_pin_shell()
                        _obj._exclude_from_output = True
                        _obj.pin().transform_keyframes(
                            local_vert=local_vert,
                            times=transform_anim["time"],
                            translations=transform_anim["translation"],
                            quaternions=transform_anim["quaternion"],
                            scales=transform_anim["scale"],
                            segments=transform_anim.get("segments", []),
                            rest_translation=rest_translation,
                        )
                    elif static_ops:
                        # Case 2: UI-assigned move/spin/scale ops. Blender
                        # has no fcurves, so the remote sim is the source of
                        # truth — include in output so PC2 can play it back.
                        _obj, _ = _setup_pin_shell()
                        pin = _obj.pin()
                        for op in static_ops:
                            t_start = float(op["t_start"])
                            t_end = float(op["t_end"])
                            transition = op.get("transition", "linear")
                            if op["op_type"] == "MOVE_BY":
                                pin.move_by(
                                    list(op["delta"]),
                                    t_start=t_start,
                                    t_end=t_end,
                                    transition=transition,
                                )
                            elif op["op_type"] == "SPIN":
                                # Center is always the object origin: in the
                                # pin-shell's local op frame that's (0,0,0).
                                pin.spin(
                                    center=[0.0, 0.0, 0.0],
                                    axis=list(op["axis"]),
                                    angular_velocity=float(op["angular_velocity"]),
                                    t_start=t_start,
                                    t_end=t_end,
                                    center_mode="absolute",
                                )
                            elif op["op_type"] == "SCALE":
                                pin.scale(
                                    scale=float(op["factor"]),
                                    t_start=t_start,
                                    t_end=t_end,
                                    center=[0.0, 0.0, 0.0],
                                    center_mode="absolute",
                                )
                            else:
                                raise ValueError(
                                    f"Unknown static op type {op['op_type']!r}"
                                )
                    else:
                        # Case 3: rest-pose static — plain collision mesh.
                        self._asset.add.tri(name, local_vert, face)
                        _static_obj = scene.add(name, obj_uuid)
                        if transform is not None:
                            _static_obj.mat4x4(transform)
                        _static_obj.pin()
                        _obj = None
                elif group_type == "SOLID":
                    reuse_from = entry.get("tetra_reuse_from")
                    transform = obj.get("transform")
                    if reuse_from is not None:
                        # Reuse tet + asset from canonical mesh
                        src = object_entries[reuse_from]
                        tet_mesh = src["_tet_mesh_result"]
                        asset_name = src["name"]
                        report(f"Reusing tetrahedralization from {asset_name} for {name}")
                    else:
                        prefix = (
                            f"Tetrahedralizing {name} "
                            f"({entry['tetra_index']}/{len(tetra_jobs)}, "
                            f"{'cached' if entry['tetra_cached'] else 'new'})"
                        )
                        report(f"{prefix}...")
                        ftw_kwargs = (
                            (ftetwild_by_uuid or {}).get(obj_uuid, {}) or {}
                        )
                        tet_mesh = entry["tri_mesh"].tetrahedralize(
                            status_callback=lambda detail, prefix=prefix: report(
                                f"{prefix}: {detail}"
                            ),
                            **ftw_kwargs,
                        )
                        entry["_tet_mesh_result"] = tet_mesh
                        completed_work += entry["tetra_weight"]
                        report(
                            f"Finished tetrahedralizing {name} "
                            f"({entry['tetra_index']}/{len(tetra_jobs)})"
                        )
                        asset_name = name
                        V_local, F, T = tet_mesh
                        # Register asset with local-space vertices
                        self._asset.add.tet(asset_name, V_local, F, T)

                    V_local, F, T = tet_mesh
                    # Add scene instance with per-instance transform
                    _obj = scene.add(asset_name, obj_uuid)
                    if transform is not None:
                        _obj.mat4x4(transform)
                    # Compute world-space V for object_info
                    if transform is not None:
                        V = self._apply_transform(V_local, transform)
                    else:
                        V = V_local
                    solid_info = {"type": "SOLID", "vert": vert, "V": V, "F": F}
                    if tet_mesh.has_surface_mapping():
                        import numpy as np

                        tri_indices, coefs = tet_mesh.surface_map
                        orig_to_sim = []
                        for bi in range(len(tri_indices)):
                            ti = tri_indices[bi]
                            tri_verts = F[ti]
                            c = coefs[bi]
                            # Frame reconstruction: p' = x0 + c1*b1 + c2*b2 + c3*n̂.
                            x0 = V[tri_verts[0]]
                            b1 = V[tri_verts[1]] - x0
                            b2 = V[tri_verts[2]] - x0
                            n = np.cross(b1, b2)
                            nlen = float(np.linalg.norm(n))
                            if nlen > 1e-10:
                                n_hat = n / nlen
                            else:
                                n_hat = np.zeros(3)
                            blender_pos = x0 + c[0] * b1 + c[1] * b2 + c[2] * n_hat
                            best_dist = float("inf")
                            best = int(tri_verts[0])
                            for k in range(len(tri_verts)):
                                d = float(sum((V[tri_verts[k]] - blender_pos) ** 2))
                                if d < best_dist:
                                    best_dist = d
                                    best = int(tri_verts[k])
                            orig_to_sim.append(best)
                        solid_info["orig_to_sim"] = orig_to_sim
                        scene.set_surface_map(obj_uuid, tri_indices, coefs, F)
                    self._object_info[obj_uuid] = solid_info
                elif group_type == "SHELL":
                    if mesh_ref and mesh_ref in canonical_meshes:
                        asset_name = canonical_asset_name[mesh_ref]
                    else:
                        asset_name = name
                        self._asset.add.tri(asset_name, local_vert, face)
                    _obj = scene.add(asset_name, obj_uuid)
                    if transform is not None:
                        _obj.mat4x4(transform)
                    self._object_info[obj_uuid] = {"type": "SHELL", "vert": vert, "V": vert, "F": face}
                    if uv is not None:
                        assert len(uv) == len(face), "UV length must match face length."
                        _obj.set_uv(uv)
                elif group_type == "ROD":
                    assert edge is not None, (
                        f"Edge data not found for rod object {name}"
                    )
                    self._asset.add.rod(name, local_vert, edge)
                    _obj = scene.add(name, obj_uuid)
                    if transform is not None:
                        _obj.mat4x4(transform)
                    self._object_info[obj_uuid] = {"type": "ROD", "vert": vert}
                else:
                    raise ValueError(f"Unknown group type: {group_type}")
                if _obj is not None and "pin" in obj:
                    pin_index = obj["pin"]
                    if verbose:
                        print(f"      > pin: {len(pin_index)}")
                    if group_type == "SOLID" and tet_mesh.has_surface_mapping():
                        # Build Blender→sim surface transfer support from the
                        # interpolation map. A pinned Blender surface vertex
                        # contributes to every simulation surface vertex whose
                        # in-plane weight is positive on the mapped triangle.
                        # Frame coefs store (c1, c2, c3); the implicit bary
                        # weights are (1-c1-c2, c1, c2), which reduce to the
                        # old bary weights when c3 ~ 0 (vertex lies on the
                        # triangle). c3 (normal offset) does not affect the
                        # pin transfer support.
                        tri_indices_pin, coefs_pin = tet_mesh.surface_map

                        def mapped_surface_vertices(blender_index: int) -> list[int]:
                            ti = tri_indices_pin[blender_index]
                            tri_verts = F[ti]
                            c = coefs_pin[blender_index]
                            w = np.array([1.0 - c[0] - c[1], c[0], c[1]])
                            sim_verts = [
                                int(tri_verts[k]) for k in range(len(tri_verts))
                                if w[k] > 1e-4
                            ]
                            if not sim_verts:
                                sim_verts = [int(tri_verts[int(np.argmax(w))])]
                            return sim_verts

                        n_surface_verts = len(vert)
                        if len(pin_index) == n_surface_verts:
                            # Use the transpose of the interpolation map:
                            # collect every simulation surface vertex that
                            # receives positive weight from a pinned Blender
                            # surface vertex.
                            sim_verts = sorted({
                                vi
                                for i in pin_index
                                for vi in mapped_surface_vertices(i)
                            })
                            holder = _obj.pin(sim_verts)
                            holder._data._blender_pin_indices = list(pin_index)
                            holder._data._tet_V = V
                            holder._data._blender_vert = vert
                            if verbose:
                                print(f"      > pin (mapped surface): {len(sim_verts)} verts")
                        else:
                            # Partial pin: each Blender pin vertex maps to the
                            # simulation surface vertices with positive
                            # interpolation weight.
                            for i in pin_index:
                                holder = _obj.pin(mapped_surface_vertices(i))
                                holder._data._blender_pin_indices = [i]
                                holder._data._tet_V = V
                                holder._data._blender_vert = vert
                    else:
                        for i in pin_index:
                            _obj.pin([i])

                resolved_stitch = obj.get("_resolved_stitch", obj.get("stitch"))
                if _obj is not None and resolved_stitch is not None:
                    stitch_data = resolved_stitch
                    stitch_name = f"{name}_stitch"
                    if verbose:
                        print(f"      > stitch: {len(stitch_data[0])} edges")
                    self._asset.add.stitch(stitch_name, stitch_data)
                    _obj.stitch(stitch_name)
                completed_work += entry["base_weight"]
                report(f"Loaded {group_type}: {name}")

        return scene
