#!/usr/bin/env python3
# File: run-all-once-gen-win.py
# Code: Claude Code
# Review: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

import argparse
from pathlib import Path


def read_examples(examples_file):
    """Read examples from the examples.txt file."""
    with open(examples_file) as f:
        examples = [line.strip() for line in f if line.strip()]
    return examples


def split_examples(examples, num_instances):
    """Split examples into N groups for parallel execution as evenly as possible."""
    if num_instances <= 0:
        raise ValueError("Number of instances must be positive")

    total = len(examples)
    base_size = total // num_instances
    remainder = total % num_instances

    chunks = []
    start = 0

    for i in range(num_instances):
        chunk_size = base_size + (1 if i < remainder else 0)
        end = start + chunk_size

        if start < total:
            chunks.append(examples[start:end])

        start = end

    return chunks


def generate_workflow(examples_chunks):
    """Generate the run-all-once-win.yml workflow file using EICE approach."""

    workflow = """# File: run-all-once-win.yml
# Code: Claude Code
# Review: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0
# Generated by: run-all-once-gen-win.py

name: All Examples (Windows Native)

on:
  workflow_dispatch:
    inputs:
      instance_type:
        description: 'EC2 instance type'
        required: true
        default: 'g6e.2xlarge'
        type: choice
        options:
          - g6.2xlarge
          - g6e.2xlarge
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-2'
        type: choice
        options:
          - us-east-1
          - us-east-2
          - ap-northeast-1

jobs:
"""

    for idx, chunk in enumerate(examples_chunks, 1):
        examples_list = " ".join(chunk)

        workflow += f"""  run-batch-{idx}:
    name: Run Batch {idx} (Windows)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{{{ github.event.inputs.region }}}}
      INSTANCE_TYPE: ${{{{ github.event.inputs.instance_type }}}}
      BRANCH: ${{{{ github.ref_name }}}}
      EXAMPLES: "{examples_list}"
      WORKDIR: C:\\ppf-contact-solver
      USER: Administrator

    steps:
      - name: Show input parameters
        run: |
          echo "## Input Parameters - Batch {idx} (Windows)"
          echo "Branch: ${{{{ github.ref_name }}}}"
          echo "Instance Type: ${{{{ github.event.inputs.instance_type }}}}"
          echo "Region: ${{{{ github.event.inputs.region }}}}"
          echo "Examples: {examples_list}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ secrets.AWS_ROLE_ARN }}}}
          aws-region: ${{{{ env.AWS_REGION }}}}
          role-duration-seconds: 21600

      - name: Find Windows Server AMI and network resources
        id: setup
        run: |
          echo "Finding latest Windows Server 2025 AMI..."
          AMI_ID=$(aws ec2 describe-images \\
            --owners amazon \\
            --filters \\
              "Name=name,Values=Windows_Server-2025-English-Full-Base-*" \\
              "Name=state,Values=available" \\
            --query 'sort_by(Images, &CreationDate)[-1].ImageId' \\
            --region "$AWS_REGION" \\
            --output text)

          if [ "$AMI_ID" = "None" ] || [ -z "$AMI_ID" ]; then
            echo "ERROR: Windows Server 2025 AMI not found in region $AWS_REGION"
            exit 1
          fi
          echo "AMI_ID=$AMI_ID" >> $GITHUB_OUTPUT
          echo "Found AMI: $AMI_ID"

          # Get GitHub Actions dedicated VPC, subnet, and security group
          VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=github-actions-vpc" --query 'Vpcs[0].VpcId' --output text)
          SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[0].SubnetId' --output text)
          SG_ID=$(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC_ID" "Name=group-name,Values=github-actions-sg" --query 'SecurityGroups[0].GroupId' --output text)

          if [ "$VPC_ID" = "None" ] || [ -z "$VPC_ID" ]; then
            echo "ERROR: github-actions-vpc not found in region $AWS_REGION"
            exit 1
          fi

          echo "::add-mask::$VPC_ID"
          echo "::add-mask::$SUBNET_ID"
          echo "::add-mask::$SG_ID"
          echo "SUBNET_ID=$SUBNET_ID" >> $GITHUB_OUTPUT
          echo "SG_ID=$SG_ID" >> $GITHUB_OUTPUT
          echo "VPC: $VPC_ID, Subnet: $SUBNET_ID, SG: $SG_ID"

      - name: Generate unique identifiers
        id: ids
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RANDOM_SUFFIX=$(head /dev/urandom | tr -dc a-z0-9 | head -c 6)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "Timestamp: $TIMESTAMP"

      - name: Create EC2 key pair
        id: keypair
        run: |
          KEY_NAME="win-batch-{idx}-${{{{ steps.ids.outputs.TIMESTAMP }}}}"
          echo "::add-mask::$KEY_NAME"
          echo "KEY_NAME=$KEY_NAME" >> $GITHUB_OUTPUT

          aws ec2 create-key-pair \\
            --key-name "$KEY_NAME" \\
            --query 'KeyMaterial' \\
            --output text > /tmp/ec2key
          chmod 600 /tmp/ec2key
          echo "Created key pair: $KEY_NAME"

      - name: Create Windows user data script
        run: |
          # Use standard SSH port 22 for EC2 Instance Connect
          sed "s/SSH_PORT_PLACEHOLDER/22/g" .github/workflows/scripts/win/user-data.ps1 > /tmp/user-data.ps1
          echo "User data script created with SSH port 22"

      - name: Launch EC2 instance
        id: instance
        run: |
          echo "Launching Windows EC2 instance..."
          INSTANCE_ID=$(aws ec2 run-instances \\
            --image-id "${{{{ steps.setup.outputs.AMI_ID }}}}" \\
            --instance-type "$INSTANCE_TYPE" \\
            --key-name "${{{{ steps.keypair.outputs.KEY_NAME }}}}" \\
            --subnet-id "${{{{ steps.setup.outputs.SUBNET_ID }}}}" \\
            --security-group-ids "${{{{ steps.setup.outputs.SG_ID }}}}" \\
            --associate-public-ip-address \\
            --user-data file:///tmp/user-data.ps1 \\
            --block-device-mappings "DeviceName=/dev/sda1,Ebs={{VolumeSize=100,VolumeType=gp3,DeleteOnTermination=true}}" \\
            --tag-specifications \\
              "ResourceType=instance,Tags=[{{Key=Name,Value=gpu-runner-win-batch-{idx}-${{{{ steps.ids.outputs.TIMESTAMP }}}}}},{{Key=ManagedBy,Value=GitHubActions}},{{Key=Purpose,Value=WindowsGPURunner}},{{Key=Workflow,Value=${{{{ github.workflow }}}}}},{{Key=RunId,Value=${{{{ github.run_id }}}}}},{{Key=Branch,Value=${{{{ env.BRANCH }}}}}},{{Key=Batch,Value={idx}}}]" \\
              "ResourceType=volume,Tags=[{{Key=Name,Value=gpu-runner-win-batch-{idx}-${{{{ steps.ids.outputs.TIMESTAMP }}}}-volume}},{{Key=ManagedBy,Value=GitHubActions}},{{Key=Purpose,Value=WindowsGPURunner}}]" \\
            --instance-initiated-shutdown-behavior terminate \\
            --query 'Instances[0].InstanceId' \\
            --region "$AWS_REGION" \\
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "Instance launched: $INSTANCE_ID"

      - name: Wait for instance ready
        run: |
          INSTANCE_ID="${{{{ steps.instance.outputs.INSTANCE_ID }}}}"
          echo "$INSTANCE_ID" > /tmp/instance_id.txt
          echo "Waiting for instance status checks..."
          aws ec2 wait instance-status-ok --instance-ids "$INSTANCE_ID"

          echo "Waiting for OpenSSH to be ready via EC2 Instance Connect..."
          for i in {{1..30}}; do
            timeout 15 aws ec2-instance-connect open-tunnel \\
              --instance-id "$INSTANCE_ID" \\
              --remote-port 22 \\
              --local-port 2222 &
            TUNNEL_PID=$!
            sleep 5

            if nc -z localhost 2222 2>/dev/null; then
              echo "SSH is responding on attempt $i"
              kill $TUNNEL_PID 2>/dev/null || true
              break
            fi

            kill $TUNNEL_PID 2>/dev/null || true
            if [ $i -eq 30 ]; then
              echo "ERROR: SSH not ready after 30 attempts"
              exit 1
            fi
            echo "Attempt $i/30: SSH not ready, waiting 10s..."
            sleep 10
          done
          echo "Instance ready for SSH connections"

      - name: Install NVIDIA driver
        run: |
          echo "Installing NVIDIA driver..."
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key .github/workflows/scripts/win/install-nvidia-driver.ps1 Administrator@localhost:C:/install_driver.ps1

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "powershell -ExecutionPolicy Bypass -File C:/install_driver.ps1"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Transfer repository to instance
        run: |
          echo "Creating and transferring repository archive..."
          git archive --format=zip --output=/tmp/repo.zip HEAD

          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key /tmp/repo.zip Administrator@localhost:C:/source.zip

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "powershell -Command \\"if (Test-Path 'C:\\\\ppf-contact-solver') {{ Remove-Item -Recurse -Force 'C:\\\\ppf-contact-solver' }}; New-Item -ItemType Directory -Path 'C:\\\\ppf-contact-solver' -Force; Expand-Archive -Path 'C:\\\\source.zip' -DestinationPath 'C:\\\\ppf-contact-solver' -Force; Remove-Item 'C:\\\\source.zip'\\""

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Run warmup.bat
        run: |
          echo "Running warmup.bat..."
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "cmd /c 'cd C:\\\\ppf-contact-solver\\\\build-win-native && warmup.bat /nopause'"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Run build.bat
        run: |
          echo "Running build.bat..."
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "cmd /c 'cd C:\\\\ppf-contact-solver\\\\build-win-native && build.bat /nopause'"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Setup CI directory
        run: |
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -i /tmp/ec2key Administrator@localhost \\
            "powershell -Command \\"New-Item -ItemType Directory -Path 'C:\\\\ci' -Force\\""

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

"""

        # Generate a step for each example
        for example in chunk:
            workflow += f"""      - name: Run {example}
        run: |
          echo "Running {example}..."
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          sed "s/EXAMPLE_PLACEHOLDER/{example}/g" .github/workflows/scripts/win/run-example.ps1 > /tmp/run_{example}.ps1

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key /tmp/run_{example}.ps1 Administrator@localhost:C:/run_{example}.ps1

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "powershell -ExecutionPolicy Bypass -File C:/run_{example}.ps1"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

"""

        # Cleanup steps
        workflow += f"""
      - name: Collect results
        if: success() || failure()
        run: |
          echo "Collecting results..."
          mkdir -p ci

          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          # Delete large binary files on remote before copying to save bandwidth
          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost \\
            "powershell -Command \\"Get-ChildItem -Path C:\\\\ppf-contact-solver\\\\cache\\\\ppf-cts\\\\ci -Recurse -Include '*.bin','*.pickle','*.ply','*.gz' -ErrorAction SilentlyContinue | Remove-Item -Force\\"" || true

          # Copy CI output from ppf-cts cache directory
          scp -P 2222 -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key "Administrator@localhost:C:/ppf-contact-solver/cache/ppf-cts/ci/*" ./ci/ || echo "No ppf-cts CI files found"

          # Also copy logs and scripts from C:\\ci
          scp -P 2222 -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key "Administrator@localhost:C:/ci/*" ./ci/ || echo "No script/log files found"

          echo "## Collected Files:"
          ls -laR ci/ || echo "No files collected"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Upload artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-win-batch-{idx}
          path: ci
          retention-days: 3

      - name: GPU information
        if: success() || failure()
        run: |
          echo "Getting GPU information..."
          INSTANCE_ID=$(cat /tmp/instance_id.txt)

          # Open tunnel for this step
          aws ec2-instance-connect open-tunnel \\
            --instance-id "$INSTANCE_ID" \\
            --remote-port 22 \\
            --local-port 2222 &
          TUNNEL_PID=$!
          sleep 5

          ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \\
            -o ServerAliveInterval=60 -o ServerAliveCountMax=10 \\
            -i /tmp/ec2key Administrator@localhost "nvidia-smi" || echo "Failed to get GPU info"

          # Close tunnel
          kill $TUNNEL_PID 2>/dev/null || true

      - name: Re-authenticate for cleanup
        if: always()
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ secrets.AWS_ROLE_ARN }}}}
          aws-region: ${{{{ env.AWS_REGION }}}}
          role-duration-seconds: 21600

      - name: Cleanup - Terminate Instance
        if: always()
        continue-on-error: true
        run: |
          if [ -n "${{{{ steps.instance.outputs.INSTANCE_ID }}}}" ]; then
            echo "Terminating instance: ${{{{ steps.instance.outputs.INSTANCE_ID }}}}"
            aws ec2 terminate-instances \\
              --instance-ids "${{{{ steps.instance.outputs.INSTANCE_ID }}}}" \\
              --region "$AWS_REGION" || true
          fi

      - name: Cleanup - Delete Key Pair
        if: always()
        continue-on-error: true
        run: |
          if [ -n "${{{{ steps.keypair.outputs.KEY_NAME }}}}" ]; then
            echo "Deleting key pair: ${{{{ steps.keypair.outputs.KEY_NAME }}}}"
            aws ec2 delete-key-pair --key-name "${{{{ steps.keypair.outputs.KEY_NAME }}}}" || true
          fi
          rm -f /tmp/ec2key

      - name: Summary
        if: always()
        run: |
          echo "## Batch {idx} Summary (Windows)"
          echo "- Examples: {examples_list}"
          echo "- Instance: ${{{{ steps.instance.outputs.INSTANCE_ID || 'Not launched' }}}}"

"""

    return workflow


def main():
    parser = argparse.ArgumentParser(
        description="Generate run-all-once-win.yml workflow file"
    )
    parser.add_argument(
        "--instances",
        type=int,
        default=5,
        help="Number of parallel instances (default: 5)",
    )

    args = parser.parse_args()

    script_dir = Path(__file__).parent
    examples_file = script_dir / "examples.txt"
    output_file = script_dir.parent / "run-all-once-win.yml"

    print(f"Reading examples from: {examples_file}")
    examples = read_examples(examples_file)
    print(f"Found {len(examples)} examples")

    print(f"Splitting into {args.instances} instance(s)")
    examples_chunks = split_examples(examples, args.instances)

    for idx, chunk in enumerate(examples_chunks, 1):
        print(f"  Batch {idx}: {len(chunk)} examples - {chunk}")

    print(f"Generating workflow file: {output_file}")
    workflow_content = generate_workflow(examples_chunks)

    with open(output_file, "w") as f:
        f.write(workflow_content)

    print(f"Successfully generated {output_file}")
    print(
        f"Total examples: {len(examples)}, Split into {len(examples_chunks)} batch(es)"
    )


if __name__ == "__main__":
    main()
