#!/usr/bin/env python3
# File: run-all.py
# Code: Claude Code
# Review: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

"""
Trigger every per-example workflow listed in examples.txt by calling
``gh workflow run <example>.yml`` once per name. Each per-example yaml
is generated by example-gen.py from the shared aws-template.yml.

Usage::

    run-all.py [instance_type] [region]

Defaults: ``g6e.2xlarge`` and ``us-east-2``. Branch is taken from the
current git HEAD.
"""

import subprocess
import sys
import time
from pathlib import Path


def read_examples_list():
    script_dir = Path(__file__).parent
    examples_file = script_dir / "examples.txt"

    if not examples_file.exists():
        print(f"Error: {examples_file} not found.")
        sys.exit(1)

    with open(examples_file, "r") as f:
        return [line.strip() for line in f if line.strip()]


def trigger_workflow(example_name, instance_type, region, branch=None):
    workflow_file = f"{example_name}.yml"

    cmd = [
        "gh",
        "workflow",
        "run",
        workflow_file,
        "-f",
        f"instance_type={instance_type}",
        "-f",
        f"region={region}",
    ]
    if branch:
        cmd.extend(["--ref", branch])

    print(f"Triggering workflow: {workflow_file}")
    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(f"  Successfully triggered {workflow_file}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  Failed to trigger {workflow_file}")
        print(f"    Error: {e.stderr}")
        return False


def main():
    instance_type = sys.argv[1] if len(sys.argv) > 1 else "g6e.2xlarge"
    region = sys.argv[2] if len(sys.argv) > 2 else "us-east-2"

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        current_branch = result.stdout.strip()
    except subprocess.CalledProcessError:
        current_branch = "unknown"

    examples = read_examples_list()
    if not examples:
        print("No examples found in examples.txt")
        sys.exit(1)

    print("Triggering per-example workflows:")
    print(f"  Branch: {current_branch}")
    print(f"  Instance type: {instance_type}")
    print(f"  Region: {region}")
    print(f"  Examples: {len(examples)}")
    print()

    failures = []
    for example in examples:
        if not trigger_workflow(example, instance_type, region, current_branch):
            failures.append(example)
        # gh CLI throttles burst dispatches; small pause keeps us under it.
        time.sleep(1)

    if failures:
        print(f"\n{len(failures)} workflow(s) failed to trigger: {failures}")
        sys.exit(1)
    print(f"\nTriggered {len(examples)} workflow(s).")


if __name__ == "__main__":
    main()
