// File: crates/ppf-cts-core/src/datamodel/session/types.rs
// Code: Claude Code
// Review: Ryoichi Ando (ryoichi.ando@zozo.com)
// License: Apache v2.0
//
// Core type definitions for the session data layer:
//
//   * `SessionInfo` / `SessionOutput`: name + path accessors.
//   * `Session`: mutable session config (proj/app/data paths, owned
//     `ParamManager`, optional reference to a built `FixedScene`).
//   * `FixedSession`: runnable result; carries `info`, `output`,
//     and a parameter snapshot.
//   * `Platform`: Windows/Unix discriminator used by the launcher
//     script and `command.{sh,bat}` selection.

use std::path::{Path, PathBuf};

use crate::datamodel::param_manager::ParamManager;

#[derive(Debug, Clone)]
pub struct SessionInfo {
    pub name: String,
    pub path: PathBuf,
}

impl SessionInfo {
    pub fn new(name: impl Into<String>, path: impl Into<PathBuf>) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct SessionOutput {
    /// Path to the session's `output/` directory.
    pub path: PathBuf,
}

impl SessionOutput {
    pub fn new(session_path: impl AsRef<Path>) -> Self {
        Self {
            path: session_path.as_ref().join("output"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Session {
    pub app_name: String,
    pub name: String,
    pub app_root: PathBuf,
    pub proj_root: PathBuf,
    pub data_dirpath: PathBuf,
    /// Counter when the session was autogenerated by
    /// `SessionManager.create(name="")`; None when the user named it.
    pub autogenerated: Option<u32>,
    pub param: ParamManager,
    /// True when the caller has built a FixedScene and bound it to
    /// this session. The actual scene lives in the consumer's storage
    /// (we don't ship it through here so the data layer stays cheap
    /// to clone).
    pub has_fixed_scene: bool,
}

impl Session {
    pub fn new(
        app_name: impl Into<String>,
        name: impl Into<String>,
        app_root: impl Into<PathBuf>,
        proj_root: impl Into<PathBuf>,
        data_dirpath: impl Into<PathBuf>,
    ) -> Self {
        Self {
            app_name: app_name.into(),
            name: name.into(),
            app_root: app_root.into(),
            proj_root: proj_root.into(),
            data_dirpath: data_dirpath.into(),
            autogenerated: None,
            param: ParamManager::new(),
            has_fixed_scene: false,
        }
    }
}

#[derive(Debug, Clone)]
pub struct FixedSession {
    pub info: SessionInfo,
    pub output: SessionOutput,
    /// Parameter snapshot captured when the FixedSession was built.
    pub param: ParamManager,
    pub proj_root: PathBuf,
}

impl FixedSession {
    /// Build from a `Session`. Skips the `delete()` + `export_fixed` +
    /// `shell_command` side effects; those are caller-driven.
    pub fn from_session(session: &Session) -> Self {
        let path = session.app_root.join(&session.name);
        let info = SessionInfo::new(&session.name, path.clone());
        let output = SessionOutput::new(&path);
        Self {
            info,
            output,
            param: session.param.copy(),
            proj_root: session.proj_root.clone(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    Windows,
    Unix,
}

impl Platform {
    /// Which platform the current build is running on.
    pub fn current() -> Self {
        if cfg!(target_os = "windows") {
            Platform::Windows
        } else {
            Platform::Unix
        }
    }

    /// Filename to use when persisting the script. `command.bat` on
    /// Windows; `command.sh` everywhere else.
    pub fn script_filename(self) -> &'static str {
        match self {
            Platform::Windows => "command.bat",
            Platform::Unix => "command.sh",
        }
    }
}
