// File: crates/ppf-cts-core/src/utils.rs
// Code: Claude Code
// Review: Ryoichi Ando (ryoichi.ando@zozo.com)
// License: Apache v2.0
//
// Engine-facing utilities. Direct port of the bits of
// frontend/_utils_.py the EffectExecutor + monitor actually call:
//
//   * `check_gpu`: nvidia-smi subprocess + SM-version check on CUDA
//     hosts; on macOS a direct Metal device query + Apple GPU family
//     check instead, no subprocess involved.
//   * `solver_busy` / `terminate_solver`: sysinfo-driven process
//     discovery + termination, replacing psutil.
//   * `is_fast_check` / `set_fast_check`: global toggle used by
//     ParamManager export to force `frames=1` in CI smoke tests.
//   * `get_cache_dir`: platform-aware cache path.
//
// What stays in Python:
//   * `in_jupyter_notebook` / `ci_name` / `get_ci_root` / `get_ci_dir`:
//     environment-detection helpers used only by notebook UX
//     paths (they don't gate engine effects).
//   * `dict_to_html_table`: display-only HTML formatter.

use std::path::{Path, PathBuf};
// Only the CUDA arm of `check_gpu` shells out via `Command` outside of
// tests (the Metal arm queries the device directly, no subprocess), so
// the non-test import is gated the same way `check_gpu_cuda` is; the
// test module below imports it separately for its own process-spawning
// helpers, which run on every platform.
#[cfg(not(target_os = "macos"))]
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};

use sysinfo::{ProcessRefreshKind, ProcessesToUpdate, RefreshKind, System};
#[cfg(unix)]
use sysinfo::Signal;

/// Process-name substring the solver binary advertises. Both
/// `solver_busy` and `terminate_solver` filter on this.
pub const SOLVER_PROCESS_NAME: &str = "ppf-contact";

/// Compute-capability targets (encoded `major*10 + minor`, so sm_86 == 86 and
/// sm_120 == 120) for which the CUDA solver ships a native SASS cubin. Device
/// LTO embeds no JIT-able PTX, so a GPU with no matching cubin cannot launch
/// any kernel; `check_gpu` gates launches against this list.
///
/// Generated by this crate's `build.rs` from
/// `crates/ppf-cts-compute/cuda/cuda_arch.txt`, which is also what both CUDA
/// builds derive their `-gencode` lines from. So this is not a copy that has to
/// be kept in step with the build, it is the same list, and editing the
/// manifest moves the build and this gate together. `ppf-cts-solver`'s
/// `build.rs` separately checks the built image against that manifest, which
/// covers the case where the toolchain did not emit what it was asked for.
pub const SUPPORTED_SM: &[u32] =
    &include!(concat!(env!("OUT_DIR"), "/cuda_arch_cubins.rs"));

/// True iff the solver ships a cubin that can run natively on a device of
/// compute capability `sm` (encoded `major*10 + minor`). SASS is binary
/// compatible forward within a major version only, so a shipped cubin `c` runs
/// on device `d` iff they share a major version and `c`'s minor `<=` `d`'s minor
/// (e.g. the sm_86 cubin also covers sm_87 and sm_89, but not sm_80). A brand
/// new major version, or a minor below every cubin we ship for that major, is
/// unsupported until a cubin is added and the solver is rebuilt.
pub fn sm_is_supported(sm: u32) -> bool {
    SUPPORTED_SM
        .iter()
        .any(|&c| c / 10 == sm / 10 && c % 10 <= sm % 10)
}

/// The AMD parts the ROCm solver ships native code objects for, as the names a
/// device reports: `gfx1100`, never `gfx11-generic`.
///
/// **A DEVICE NEVER NAMES A GENERIC TARGET, WHICH IS WHY THIS LIST IS EXPANDED
/// RATHER THAN COPIED.** `hipDeviceProp_t::gcnArchName` gives a specific part,
/// while `rocm_arch.txt` is mostly generic targets, each emitting one code
/// object for a whole family. `build.rs` expands the first through
/// `crates/ppf-cts-compute/rocm/generic_targets.txt`, whose membership is read
/// from the pinned toolchain's own documentation rather than assumed; that file
/// records the commit and why guessing is wrong in both directions.
///
/// **THIS IS A COMPILE-COVERAGE CLAIM AND NOT A TESTED-HARDWARE CLAIM.** No AMD
/// Radeon hardware is available to this project, so nothing in this list has
/// ever executed a kernel. Any refusal built on it must therefore be worded so a
/// user cannot read it as the second.
pub const SUPPORTED_GFX: &[&str] =
    &include!(concat!(env!("OUT_DIR"), "/rocm_arch_gfx.rs"));

/// True iff the solver ships a code object that runs natively on a device whose
/// `gcnArchName` is `arch`.
///
/// **THE COMPARISON DROPS THE TARGET-ID FEATURES AND KEEPS THE PART.** A real
/// device reports its architecture with the feature flags appended,
/// `gfx90a:sramecc+:xnack-`, and those describe the mode the device is in rather
/// than which code object can run on it. Matching the whole string would refuse
/// every machine that has xnack enabled, which is most of them on the parts that
/// support it. Everything from the first `:` is therefore cut before the
/// comparison, and the remainder must match a shipped part exactly: unlike CUDA
/// SASS, an AMD code object is not forward compatible within a family, which is
/// the whole reason the generic targets exist.
pub fn gfx_is_supported(arch: &str) -> bool {
    let part = arch.split(':').next().unwrap_or(arch).trim();
    SUPPORTED_GFX.iter().any(|&c| c == part)
}

/// Human-readable `gfx1100, gfx1101, ...` rendering of [`SUPPORTED_GFX`] for
/// error messages, on the same terms as [`supported_sm_list`].
#[cfg_attr(
    any(target_os = "macos", feature = "cpu"),
    allow(dead_code)
)]
pub fn supported_gfx_list() -> String {
    SUPPORTED_GFX.join(", ")
}

/// Human-readable `sm_86, sm_89, ...` rendering of [`SUPPORTED_SM`] for error
/// messages. Only reachable from non-test code via `check_gpu_cuda`, so a
/// non-test build sees no call site wherever that arm is `cfg`'d out: on macOS,
/// under the `cpu` feature, and under `rocm`, in all of which [`check_gpu`]
/// returns before reaching the CUDA arm.
///
/// What reads it in those configurations is the test
/// `check_gpu_error_messages_match_python` in this file's `tests` module, which
/// pins the `SmUnsupported` message and asserts that the supported set is
/// spelled out in it, so dropping the rendering costs that message the list a
/// user needs in order to act on it.
#[cfg_attr(
    any(target_os = "macos", feature = "cpu", feature = "rocm"),
    allow(dead_code)
)]
fn supported_sm_list() -> String {
    SUPPORTED_SM
        .iter()
        .map(|s| format!("sm_{s}"))
        .collect::<Vec<_>>()
        .join(", ")
}

// ---------------------------------------------------------------------------
// is_fast_check / set_fast_check
//
// Process-wide flag used by ParamManager export to clamp frames=1 in
// CI / smoke contexts. AtomicBool replaces the Python class-attribute.

static FAST_CHECK: AtomicBool = AtomicBool::new(false);

pub fn is_fast_check() -> bool {
    FAST_CHECK.load(Ordering::Relaxed)
}

pub fn set_fast_check(enabled: bool) {
    FAST_CHECK.store(enabled, Ordering::Relaxed);
}

// ---------------------------------------------------------------------------
// Cache directory.

/// Platform-aware cache directory for the tree at `base_dir`.
///
/// ONE RESOLVER, NOT TWO. This delegates to
/// `datamodel::app::default_cache_dir` rather than answering the same question
/// with its own code. A second implementation anchored at `current_dir()` would
/// agree with it only while the caller happened to have chdir'd to the tree
/// root; sharing one implementation is what puts a packaged tree's export, CI
/// and render-temp directories beside its asset cache instead of in `$HOME`.
///
/// `base_dir` is the tree root, the same value `App.get_data_dirpath` passes.
/// The Python bindings resolve it from `frontend/__file__`, which is the only
/// place that reliably knows it: `current_dir()` is wherever the user happened
/// to run from, and a cdylib's `current_exe()` is the interpreter.
pub fn get_cache_dir(base_dir: &Path) -> PathBuf {
    let home = std::env::var_os("HOME").map(PathBuf::from);
    let dir = crate::datamodel::app::default_cache_dir(base_dir, home.as_deref());
    let _ = std::fs::create_dir_all(&dir);
    dir
}

// ---------------------------------------------------------------------------
// GPU check.

#[derive(Debug, thiserror::Error)]
pub enum GpuError {
    #[error("nvidia-smi not found. An NVIDIA GPU with CUDA support is required.")]
    NvidiaSmiMissing,
    #[error("nvidia-smi failed. An NVIDIA GPU with CUDA support is required.")]
    NvidiaSmiFailed,
    #[error(
        "GPU '{name}' has compute capability sm_{actual}, which this solver build does not \
         support. Supported architectures: {supported}. The CUDA kernels ship as native code \
         per architecture with no JIT fallback, so a GPU outside this set cannot run; a newer \
         GPU generation requires a solver rebuild with its architecture added."
    )]
    SmUnsupported {
        name: String,
        actual: u32,
        supported: String,
    },
    #[error("No NVIDIA GPU detected. An NVIDIA GPU is required to run the solver.")]
    NoGpuDetected,
    // THE ADVICE VARIES BY PLATFORM AND THE FIRST SENTENCE DOES NOT. A Windows
    // machine has no amdgpu kernel module, no /dev/kfd and no render group to
    // join, so the Linux wording sent that user looking for device nodes their
    // system cannot have, and the Windows distribution shipped exactly that
    // text. The sentence before the advice is fixed because it travels: the
    // solver prints this as `--probe`'s `unusable:` detail, `frontend._backends_`
    // passes it through verbatim, and the frontend and add-on tests match on it.
    #[error("No AMD GPU detected. {advice}")]
    NoAmdGpuDetected { advice: &'static str },
    #[error(
        "The HIP runtime could not be asked what devices are present (hipError \
         {status}). The runtime ships beside this program, so this usually means the \
         distribution is incomplete rather than that the machine has no GPU."
    )]
    HipRuntimeUnavailable { status: i32 },
    #[error(
        "AMD GPU '{arch}' is not one this solver build ships code for. It ships: \
         {supported}. An AMD code object carries no forward compatibility between gfx \
         numbers, so a part outside this set cannot run and needs a rebuild with its \
         target added. NOTE that this list is what was COMPILED, not what has been \
         tested: this project has no AMD hardware, so no part in it has ever executed \
         a kernel."
    )]
    GfxUnsupported { arch: String, supported: String },
    #[error(
        "CUDA_VISIBLE_DEVICES is set to '{spec}', which selects no GPU this machine has, so \
         CUDA sees no device at all. Detected: {detected}."
    )]
    VisibleDevicesUnsatisfied { spec: String, detected: String },
    #[error(
        "CUDA device 0 cannot be identified from CUDA_VISIBLE_DEVICES='{spec}' on this \
         multi-GPU machine. Select a GPU by UUID. Detected: {detected}."
    )]
    VisibleDeviceAmbiguous { spec: String, detected: String },
    #[error(
        "No Metal-capable GPU detected on this host. MTLCreateSystemDefaultDevice returned no \
         device, so there is no GPU visible to Metal to run the solver on. On real Apple \
         Silicon hardware this should not happen; it is expected only in an environment with no \
         GPU access (for example, some headless CI sandboxes or a VM with no GPU passthrough)."
    )]
    MetalDeviceMissing,
    #[error(
        "GPU '{name}' does not support the Metal GPU family this solver build requires \
         ({required}). This solver's Metal backend targets Apple Silicon Macs only; an Intel \
         Mac with a non-Apple (AMD or Intel integrated) GPU is unsupported, and there is no \
         fallback."
    )]
    MetalFamilyUnsupported { name: String, required: String },
}

/// Position in `rows` of the device CUDA exposes as its own device 0.
///
/// `rows` is `(index, uuid)` per device in the order `nvidia-smi` reported
/// them, and `visible` is the value of `CUDA_VISIBLE_DEVICES`, or `None` when
/// it is not set. Applying that variable is the caller's job: `nvidia-smi`
/// lists every device on the machine whatever the variable says (measured on a
/// four-GPU Windows host, where setting it to `2` still prints rows 0 through
/// 3), so a caller that reads the first row instead describes and validates a
/// GPU the solver may never touch.
///
/// The variable is a comma-separated list and CUDA's device 0 is its first
/// entry, named either by index or by UUID, for which a unique prefix is
/// enough. A value that is empty or all whitespace exposes no device, while
/// `None` leaves visibility unrestricted.
///
/// `None` means the value is absent, ambiguous, or names no detected device.
pub fn visible_device_position(rows: &[(u32, &str)], visible: Option<&str>) -> Option<usize> {
    let Some(spec) = visible else {
        return (rows.len() == 1).then_some(0);
    };
    let selector = spec
        .split(',')
        .next()
        .map(str::trim)
        .filter(|token| !token.is_empty());
    let Some(token) = selector else {
        return None;
    };
    if let Ok(index) = token.parse::<u32>() {
        if rows.len() != 1 {
            return None;
        }
        return rows.iter().position(|&(i, _)| i == index);
    }
    let mut matches = rows
        .iter()
        .enumerate()
        .filter(|(_, (_, uuid))| uuid.starts_with(token));
    let (position, _) = matches.next()?;
    matches.next().is_none().then_some(position)
}

/// One device as `--query-gpu=index,uuid,<fields>,name` reported it.
///
/// Both callers query the identity columns first and `name` last, so a comma
/// inside a marketing name cannot shift the columns that are read by position.
pub struct GpuRow {
    pub index: u32,
    pub uuid: String,
    pub fields: Vec<String>,
    pub name: String,
}

/// Parse `--query-gpu=index,uuid,<field_count fields>,name --format=csv,noheader`.
///
/// A row whose index does not parse, or that is missing columns, is dropped:
/// it carries no device this function can name.
pub fn parse_gpu_rows(stdout: &str, field_count: usize) -> Vec<GpuRow> {
    let mut rows = Vec::new();
    for line in stdout.lines().filter(|l| !l.trim().is_empty()) {
        let parts: Vec<&str> = line.splitn(field_count + 3, ',').collect();
        if parts.len() != field_count + 3 {
            continue;
        }
        let Ok(index) = parts[0].trim().parse::<u32>() else {
            continue;
        };
        rows.push(GpuRow {
            index,
            uuid: parts[1].trim().to_string(),
            fields: parts[2..2 + field_count]
                .iter()
                .map(|f| f.trim().to_string())
                .collect(),
            name: parts[field_count + 2].trim().to_string(),
        });
    }
    rows
}

/// The row of `rows` the solver will run on, honoring `CUDA_VISIBLE_DEVICES`.
pub fn selected_gpu_row(rows: &[GpuRow]) -> Result<&GpuRow, GpuError> {
    if rows.is_empty() {
        return Err(GpuError::NoGpuDetected);
    }
    let visible = std::env::var("CUDA_VISIBLE_DEVICES").ok();
    let pairs: Vec<(u32, &str)> = rows.iter().map(|r| (r.index, r.uuid.as_str())).collect();
    match visible_device_position(&pairs, visible.as_deref()) {
        Some(pos) => Ok(&rows[pos]),
        None => {
            let spec = visible.unwrap_or_default();
            let detected = rows
                .iter()
                .map(|r| format!("{} ({})", r.index, r.name))
                .collect::<Vec<_>>()
                .join(", ");
            let selector = spec.split(',').next().map(str::trim).unwrap_or("");
            if rows.len() > 1 && (selector.is_empty() || selector.parse::<u32>().is_ok()) {
                Err(GpuError::VisibleDeviceAmbiguous { spec, detected })
            } else {
                Err(GpuError::VisibleDevicesUnsatisfied { spec, detected })
            }
        }
    }
}

/// Human-readable rendering of the minimum Metal GPU family gate, for
/// [`GpuError::MetalFamilyUnsupported`] messages.
#[cfg(any(target_os = "macos", test))]
// Dead in a `cpu` build and live in every other one, which is the same shape
// `check_gpu_cuda` is annotated for: `check_gpu` takes its cpu arm first, so
// nothing on macOS reaches the Metal arm or anything it names. A bare `allow`
// would hide a genuine disuse in the builds where this IS reached.
#[cfg_attr(feature = "cpu", allow(dead_code))]
const METAL_MIN_FAMILY_DESC: &str = "Apple7 (the M1 / A14 generation) or newer";

/// Check that a GPU capable of running this solver build is present.
///
/// Dispatches on host platform: the CUDA arm shells out to `nvidia-smi`
/// and gates the selected device on [`SUPPORTED_SM`] cubin coverage; the
/// macOS/Metal arm queries the default Metal device in process and gates
/// on Apple GPU device family, since `nvidia-smi` does not exist on macOS.
///
/// **The `cpu` feature short-circuits both**, and the reason is that the platform
/// is the wrong question for that build. Dispatching on `target_os` alone means a
/// Linux host running the CPU backend is asked for `nvidia-smi` and told "An
/// NVIDIA GPU with CUDA support is required", which is both false and, worse,
/// pre-empts the backend's own message: the CPU backend refuses a scene it cannot
/// solve BY NAME AND BY COUNT at `initialize()`, and that refusal is what the
/// reader needs. A gate in front of it that names a different, wrong reason
/// converts a precise diagnosis into a misleading one. Measured: every one of the
/// 24 example notebooks died here, none of them reaching the backend at all.
///
/// This is a capability question, so the flag is owned by this crate and
/// dependents cascade `cpu = ["ppf-cts-core/cpu"]`. A single toggle keeps the
/// definitions from drifting.
/// Whether this build needs an NVIDIA driver, and therefore whether the
/// driver-version check and the `nvidia-smi` diagnostic dumps apply.
///
/// It exists because the frontend was asking the PLATFORM instead. Gating on
/// `platform.system() != "Darwin"` is right for exactly two of the four backends
/// and wrong for the CPU one on Linux, where it demands an NVIDIA driver version
/// from a build that will never launch a CUDA kernel. That is the same mistake
/// [`check_gpu`] made, in a different language, so the answer is published once
/// here rather than re-derived per caller.
///
/// A capability, not a platform: read it as "does this build talk to CUDA",
/// which is what every caller actually wants to know.
pub fn needs_nvidia_driver() -> bool {
    // A ROCm build needs the AMD kernel driver and `/dev/kfd`, not an NVIDIA
    // one, so it answers NO here for the same reason the CPU build does. The
    // answer is published from this one function rather than recomputed in
    // Python, which is why the flag has to reach it rather than being handled
    // only at the call site.
    !cfg!(feature = "cpu")
        && !cfg!(feature = "rocm")
        && !cfg!(target_os = "macos")
}

pub fn check_gpu() -> Result<(), GpuError> {
    #[cfg(feature = "cpu")]
    {
        Ok(())
    }
    #[cfg(all(not(feature = "cpu"), not(feature = "rocm"), target_os = "macos"))]
    {
        check_gpu_metal()
    }
    // THE ROCm ARM MUST NOT BE `rocminfo`, and that is a packaging constraint
    // rather than a preference: `rocminfo` is a ROCm package, so reaching for it
    // would put a ROCm installation back in front of an end user, which is the
    // one thing the distribution exists to avoid. The device query belongs in an
    // in-process probe against the BUNDLED runtime, the shape `check_gpu_metal`
    // already has, and that is what `check_gpu_rocm` below is. The alternative
    // this rules out is not just `rocminfo`: a preflight that asked `nvidia-smi`
    // would refuse every correct ROCm machine, which is what the non-macOS
    // default arm does and why ROCm needs its own.
    #[cfg(all(
        not(feature = "cpu"),
        feature = "rocm",
        any(target_os = "linux", target_os = "windows")
    ))]
    {
        check_gpu_rocm()
    }
    // NOTHING ELSE RUNS ROCm, so this arm is macOS and whatever else cargo is
    // pointed at. It admits rather than refusing: there is no HIP runtime to
    // ask, and the backend's own `be_open` fails by name if such a build is ever
    // produced and run.
    #[cfg(all(
        not(feature = "cpu"),
        feature = "rocm",
        not(any(target_os = "linux", target_os = "windows"))
    ))]
    {
        Ok(())
    }
    #[cfg(all(not(feature = "cpu"), not(feature = "rocm"), not(target_os = "macos")))]
    {
        check_gpu_cuda()
    }
}

// The ROCm probe compiled by this crate's `build.rs` from `cpp/rocm_probe.cpp`,
// against the SDK's own headers. Declared here rather than mirrored: see that
// file's header for why `hipDeviceProp_t` may not be re-declared. A plain
// comment, not a doc comment: rustdoc documents no extern block, so `///` here
// is an `unused_doc_comments` warning rather than documentation.
#[cfg(all(
    not(feature = "cpu"),
    feature = "rocm",
    any(target_os = "linux", target_os = "windows")
))]
extern "C" {
    fn ppf_cts_core_rocm_probe(
        out_count: *mut std::ffi::c_int,
        out_arch: *mut std::ffi::c_char,
        out_arch_cap: usize,
        out_status: *mut std::ffi::c_int,
    ) -> std::ffi::c_int;
}

/// ROCm arm of [`check_gpu`]: asks the BUNDLED HIP runtime in process, with no
/// subprocess and no ROCm installation.
///
/// **IT MUST NOT BE `rocminfo`**, which is a ROCm package: reaching for it would
/// put an installation back in front of an end user, which is the one thing the
/// distribution exists to avoid. The runtime this calls is the one shipped
/// beside the binary.
///
/// **AND IT GATES ON THE ARCHITECTURE ONLY ON THE AMD PLATFORM.** An
/// `HIP_PLATFORM=nvidia` build is the staging leg: HIP is a shim over CUDA
/// there, the device is an NVIDIA GPU, and `SUPPORTED_GFX` describes nothing it
/// runs, so gating on it would refuse every machine that build targets. The
/// platform is published as a cfg by `build.rs` rather than guessed here.
#[cfg(all(
    not(feature = "cpu"),
    feature = "rocm",
    any(target_os = "linux", target_os = "windows")
))]
fn check_gpu_rocm() -> Result<(), GpuError> {
    let reported = rocm_probe()?;
    // The staging platform reports a device NAME here, not a gfx target, so
    // there is nothing for SUPPORTED_GFX to say about it.
    #[cfg(rocm_platform_nvidia)]
    {
        let _ = reported;
        return Ok(());
    }
    #[cfg(not(rocm_platform_nvidia))]
    {
        if gfx_is_supported(&reported) {
            Ok(())
        } else {
            Err(GpuError::GfxUnsupported {
                arch: reported,
                supported: supported_gfx_list(),
            })
        }
    }
}

/// Ask the bundled HIP runtime for its first device and return what that device
/// calls itself: the gfx target on the AMD platform, the device name on the
/// staging one. [`check_gpu_rocm`] gates on the answer and
/// [`rocm_device_arch`] reports it.
#[cfg(all(
    not(feature = "cpu"),
    feature = "rocm",
    any(target_os = "linux", target_os = "windows")
))]
fn rocm_probe() -> Result<String, GpuError> {
    const CAP: usize = 256;
    let mut count: std::ffi::c_int = 0;
    let mut status: std::ffi::c_int = 0;
    let mut arch = [0 as std::ffi::c_char; CAP];
    // SAFETY: the three out pointers address live locals for the whole call and
    // the probe writes at most CAP bytes into `arch`, NUL-terminating within it.
    let rc = unsafe {
        ppf_cts_core_rocm_probe(&mut count, arch.as_mut_ptr(), CAP, &mut status)
    };
    if rc != 0 {
        return Err(GpuError::HipRuntimeUnavailable { status: status as i32 });
    }
    if count <= 0 {
        // A MACHINE WITH NO AMD GPU ARRIVES HERE RATHER THAN FAILING TO LOAD, on
        // Windows especially: `amdhip64_7.dll` loads without an AMD driver
        // (measured on a Windows machine with no AMD GPU, which is why
        // bundle.bat's import gate can load the ROCm cdylib there), so the
        // runtime answers "zero devices"
        // instead of the program failing to start. That makes this message the
        // only thing such a user sees, so it names what they can act on.
        return Err(GpuError::NoAmdGpuDetected {
            advice: if cfg!(target_os = "windows") {
                "This is a ROCm build, so it needs an AMD GPU with AMD's Windows \
                 driver installed. No ROCm installation is required: the runtime \
                 ships with this program."
            } else {
                "This is a ROCm build, so it needs an AMD GPU with the amdgpu \
                 kernel driver loaded and /dev/kfd present, and the user running \
                 it must be in the group that owns /dev/kfd and /dev/dri/render*. \
                 No ROCm installation is required: the runtime ships with this \
                 program."
            },
        });
    }
    // SAFETY: the probe NUL-terminated `arch` within CAP on the success path.
    Ok(unsafe { std::ffi::CStr::from_ptr(arch.as_ptr()) }
        .to_string_lossy()
        .into_owned())
}

/// What the first AMD device calls itself, for a hardware report, or `None`
/// when this build has no HIP runtime to ask or the runtime reports no device.
///
/// A REPORT, NOT A GATE: [`check_gpu`] is what refuses a run. It is declared on
/// every build so a caller matching on [`backend`] can name it in the `Rocm`
/// arm without a feature of its own, and only a ROCm build reaches that arm.
pub fn rocm_device_arch() -> Option<String> {
    #[cfg(all(
        not(feature = "cpu"),
        feature = "rocm",
        any(target_os = "linux", target_os = "windows")
    ))]
    {
        rocm_probe().ok()
    }
    #[cfg(not(all(
        not(feature = "cpu"),
        feature = "rocm",
        any(target_os = "linux", target_os = "windows")
    )))]
    {
        None
    }
}

/// CUDA arm of [`check_gpu`]: asks `nvidia-smi` for `index,uuid,compute_cap,name`
/// with `CUDA_VISIBLE_DEVICES` removed from the subprocess environment, so every
/// device on the machine is enumerated, then applies that variable in code (see
/// [`selected_gpu_row`]) and gates the row the solver will actually launch on
/// against [`SUPPORTED_SM`] cubin coverage.
///
/// Its one caller is [`check_gpu`], which selects this arm only when neither the
/// `cpu` nor the `rocm` feature is on, while the `cfg` on this function admits
/// it on target alone. A `cpu` or `rocm` build therefore compiles it with no
/// call site, a ROCm machine needing the AMD kernel driver rather than an
/// NVIDIA one. No test calls it either: the tests cover the pieces it composes,
/// `parse_gpu_rows`, `selected_gpu_row`, `sm_is_supported` and the error
/// strings, rather than the `nvidia-smi` subprocess it runs.
#[cfg_attr(any(feature = "cpu", feature = "rocm"), allow(dead_code))]
#[cfg(not(target_os = "macos"))]
fn check_gpu_cuda() -> Result<(), GpuError> {
    let output = match Command::new("nvidia-smi")
        .args([
            "--query-gpu=index,uuid,compute_cap,name",
            "--format=csv,noheader,nounits",
        ])
        // Enumerate every device and apply CUDA_VISIBLE_DEVICES in code; see
        // `visible_device_position` for why nvidia-smi's own handling of it is
        // not relied on.
        .env_remove("CUDA_VISIBLE_DEVICES")
        .output()
    {
        Ok(o) => o,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(GpuError::NvidiaSmiMissing);
        }
        Err(_) => {
            return Err(GpuError::NvidiaSmiFailed);
        }
    };
    if !output.status.success() {
        return Err(GpuError::NvidiaSmiFailed);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let rows = parse_gpu_rows(&stdout, 1);
    // Validate the GPU the solver will actually launch on, which is the one
    // CUDA_VISIBLE_DEVICES selects, not the first row nvidia-smi prints. On a
    // machine whose first GPU is a display adapter below SUPPORTED_SM, reading
    // row 0 rejects a run that the selected compute card could serve.
    let selected = selected_gpu_row(&rows)?;
    let sm_ver = match selected.fields[0].replace('.', "").parse::<u32>() {
        Ok(v) => v,
        Err(_) => return Err(GpuError::NvidiaSmiFailed),
    };
    if !sm_is_supported(sm_ver) {
        return Err(GpuError::SmUnsupported {
            name: selected.name.clone(),
            actual: sm_ver,
            supported: supported_sm_list(),
        });
    }
    Ok(())
}

// Runtime probe compiled by build.rs from cpp/metal_probe.mm, linked
// only on macOS (see build.rs). Deliberately narrow: this is a
// pre-flight capability query, not a copy of the real Metal backend's
// own device setup in crates/ppf-cts-compute/metal/.
#[cfg(target_os = "macos")]
#[cfg_attr(feature = "cpu", allow(dead_code))]
extern "C" {
    fn ppf_cts_core_metal_probe(
        out_device_found: *mut bool,
        out_family_ok: *mut bool,
        out_name: *mut std::os::raw::c_char,
        out_name_cap: std::os::raw::c_ulong,
    );
}

/// Metal arm of [`check_gpu`]: queries the default Metal device directly, with
/// no subprocess, and gates on Apple GPU family membership. Runtime resource
/// limits remain the backend context's responsibility because they apply to
/// individual pipelines and allocations rather than this preflight check.
#[cfg(target_os = "macos")]
#[cfg_attr(feature = "cpu", allow(dead_code))]
fn check_gpu_metal() -> Result<(), GpuError> {
    const NAME_CAP: usize = 256;
    let mut device_found = false;
    let mut family_ok = false;
    let mut name_buf = [0 as std::os::raw::c_char; NAME_CAP];
    // Safety: `device_found`/`family_ok` are live `bool` locals on this
    // stack frame, and `name_buf` is a live `NAME_CAP`-byte buffer whose
    // capacity is passed alongside it; the C probe never writes past
    // `out_name_cap` bytes and always NUL-terminates within it.
    unsafe {
        ppf_cts_core_metal_probe(
            &mut device_found,
            &mut family_ok,
            name_buf.as_mut_ptr(),
            NAME_CAP as std::os::raw::c_ulong,
        );
    }
    if !device_found {
        return Err(GpuError::MetalDeviceMissing);
    }
    if !family_ok {
        // Safety: the probe always NUL-terminates `name_buf` within its
        // capacity, even on the found-but-unsupported-family path.
        let name = unsafe { std::ffi::CStr::from_ptr(name_buf.as_ptr()) }
            .to_string_lossy()
            .into_owned();
        return Err(GpuError::MetalFamilyUnsupported {
            name,
            required: METAL_MIN_FAMILY_DESC.to_string(),
        });
    }
    Ok(())
}


/// Which backend a build targets.
///
/// AN ENUM RATHER THAN A STRING, so a caller deciding what to probe writes an
/// exhaustive match and a fourth backend cannot be added without every such
/// caller being made to say what it does about it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    Cuda,
    Metal,
    Rocm,
    Cpu,
}

impl Backend {
    /// The lowercase word for this backend.
    ///
    /// These match `PPF_BACKEND` in `ppf-cts-solver`, which is what
    /// `ppf-contact-solver --backend` prints and what the `.ppf-backend` marker
    /// beside the artifacts holds, so a reader comparing what a panel says
    /// against either of those gets the same word.
    pub fn name(self) -> &'static str {
        match self {
            Backend::Cuda => "cuda",
            Backend::Metal => "metal",
            Backend::Rocm => "rocm",
            Backend::Cpu => "cpu",
        }
    }
}

/// Which backend THIS build targets.
///
/// The arms are [`check_gpu`]'s, deliberately: a build that asks for an NVIDIA
/// device is the same build that reports CUDA, and a build that asks the HIP
/// runtime is the one that reports ROCm, so deriving both from one set of
/// `cfg`s is what stops a panel naming a backend the preflight would refuse.
/// Without the ROCm arm a ROCm server reported itself as `cuda` and asked
/// `nvidia-smi` for its hardware rows.
///
/// The server cannot ask the SOLVER binary instead, which would be the rule
/// elsewhere in this tree. It never resolves that path: the frontend spawns the
/// solver, so at the moment the server probes its hardware there is no artifact
/// here to interrogate.
pub fn backend() -> Backend {
    #[cfg(feature = "cpu")]
    {
        Backend::Cpu
    }
    #[cfg(all(not(feature = "cpu"), feature = "rocm"))]
    {
        Backend::Rocm
    }
    #[cfg(all(not(feature = "cpu"), not(feature = "rocm"), target_os = "macos"))]
    {
        Backend::Metal
    }
    #[cfg(all(not(feature = "cpu"), not(feature = "rocm"), not(target_os = "macos")))]
    {
        Backend::Cuda
    }
}

/// What the default Metal device calls itself, and how much memory it will
/// work with.
#[cfg(target_os = "macos")]
pub struct MetalDeviceInfo {
    /// The device's own localized name, for example `Apple M2 Max`.
    pub name: String,
    /// `recommendedMaxWorkingSetSize`, in bytes. Apple Silicon has no separate
    /// VRAM, memory being unified with the CPU, so this is the working set
    /// Metal recommends staying under rather than a card's capacity.
    pub working_set_bytes: u64,
    /// The highest `MTLGPUFamilyApple<N>` the device supports, as N, or `None`
    /// when it supports no Apple family at all. This is the Metal analogue of a
    /// CUDA SM level, and the same number [`check_gpu`] gates on: Apple7 is the
    /// minimum the backend targets, so a device reporting `None` here is one
    /// that preflight refuses.
    pub apple_family: Option<u32>,
}

// Descriptive companion to `ppf_cts_core_metal_probe`, compiled from the same
// cpp/metal_probe.mm. Kept separate there so a failure feeding a panel can
// never reach what the preflight decides.
#[cfg(target_os = "macos")]
extern "C" {
    fn ppf_cts_core_metal_device_info(
        out_name: *mut std::os::raw::c_char,
        out_name_cap: std::os::raw::c_ulong,
        out_working_set_bytes: *mut u64,
        out_apple_family: *mut std::os::raw::c_uint,
    ) -> bool;
}

/// A live sample of what the GPU is doing, for the "Realtime Statistics" rows.
#[cfg(target_os = "macos")]
pub struct MetalUsage {
    /// System-wide GPU utilization, 0 to 100. The counter Activity Monitor
    /// shows, and like nvidia-smi's it describes the DEVICE rather than this
    /// process.
    pub device_util_pct: u32,
    /// Bytes of system memory the accelerator currently has in use, or `None`
    /// when the registry did not publish that key.
    pub in_use_bytes: Option<u64>,
}

// The live counter, read from the IOAccelerator registry entry rather than from
// Metal, which publishes no device-wide utilization figure.
#[cfg(target_os = "macos")]
extern "C" {
    fn ppf_cts_core_metal_usage(
        out_device_util_pct: *mut std::os::raw::c_uint,
        out_in_use_bytes: *mut u64,
    ) -> bool;
}

/// Sample the GPU's current utilization, or `None` when no counter could be
/// read.
///
/// CALLED ON EVERY STATUS POLL, so it does no subprocess work: the CUDA side
/// spawns nvidia-smi for the same answer, and this is a registry read in
/// process. `None` here means the rows are omitted, never that anything failed
/// loudly, because the keys it reads are registry properties rather than
/// published API and a macOS that renames one must cost a row and nothing more.
#[cfg(target_os = "macos")]
pub fn metal_usage() -> Option<MetalUsage> {
    let mut pct: std::os::raw::c_uint = 0;
    let mut in_use: u64 = 0;
    // Safety: both are live locals on this stack frame, and the probe writes
    // each at most once through the pointer it was given.
    let found = unsafe { ppf_cts_core_metal_usage(&mut pct, &mut in_use) };
    if !found {
        return None;
    }
    Some(MetalUsage {
        device_util_pct: pct as u32,
        in_use_bytes: (in_use > 0).then_some(in_use),
    })
}

/// Describe the default Metal device, or `None` when there is no such device.
///
/// PURELY DESCRIPTIVE, AND NOTHING GATES ON IT. `check_gpu` is what decides
/// whether this host may run; this only says what the panel shows. So a `None`
/// here means a row is omitted, never that a run is refused.
#[cfg(target_os = "macos")]
pub fn metal_device_info() -> Option<MetalDeviceInfo> {
    const NAME_CAP: usize = 256;
    let mut name_buf = [0 as std::os::raw::c_char; NAME_CAP];
    let mut working_set_bytes: u64 = 0;
    let mut apple_family: std::os::raw::c_uint = 0;
    // Safety: `name_buf` is a live NAME_CAP-byte buffer whose capacity is
    // passed alongside it and which the probe always NUL-terminates within, and
    // `working_set_bytes` and `apple_family` are live locals on this stack
    // frame.
    let found = unsafe {
        ppf_cts_core_metal_device_info(
            name_buf.as_mut_ptr(),
            NAME_CAP as std::os::raw::c_ulong,
            &mut working_set_bytes,
            &mut apple_family,
        )
    };
    if !found {
        return None;
    }
    // Safety: NUL-terminated within capacity by the probe, on every path that
    // reports a device.
    let name = unsafe { std::ffi::CStr::from_ptr(name_buf.as_ptr()) }
        .to_string_lossy()
        .into_owned();
    Some(MetalDeviceInfo {
        name,
        working_set_bytes,
        // Zero is the probe's "no Apple family at all", which is a real answer
        // about the device rather than a failure, so it becomes None here and
        // the row is simply not drawn.
        apple_family: (apple_family > 0).then_some(apple_family as u32),
    })
}

// ---------------------------------------------------------------------------
// Process discovery + termination.

/// Construct and populate a `System` snapshot scoped to process info.
/// All three process helpers read only name/status/parent, so a
/// process-only refresh is sufficient. Centralizing the construction
/// keeps the refresh decision in one place.
fn scan_solver_system() -> System {
    let mut sys = System::new_with_specifics(
        RefreshKind::new().with_processes(ProcessRefreshKind::new()),
    );
    sys.refresh_processes(ProcessesToUpdate::All, true);
    sys
}

/// True iff `proc` is a live (non-zombie) solver process, i.e. its
/// name contains `SOLVER_PROCESS_NAME`.
fn is_live_solver(proc: &sysinfo::Process) -> bool {
    proc.name().to_string_lossy().contains(SOLVER_PROCESS_NAME)
        && !matches!(proc.status(), sysinfo::ProcessStatus::Zombie)
}

/// Whether this process has been told it is one worker among several on the
/// host, so a solver scan must see only its OWN descendants.
///
/// THE SCOPING COMES FROM A RUNTIME SIGNAL, WHICH IS THE WHOLE POINT.
/// `ppf-cts-server`'s monitor and executor both record that the descendant-only
/// pair is what a multi-worker runner has to be re-keyed onto, and that the
/// signal cannot be a build feature: no backend has a flag standing in for
/// "under a parallel runner". An environment variable is a property of the
/// PROCESS, which is exactly the granularity the question has.
///
/// Unset is the default and is host-global, which is the conservative answer: a
/// single-worker host wants to know about any solver at all, and two scopings
/// agree there.
pub fn worker_scoped_scan() -> bool {
    std::env::var_os("PPF_SOLVER_SCAN_DESCENDANTS").is_some()
}

/// True iff a live solver process is running.
///
/// Host-global by default; own-descendants-only when
/// `PPF_SOLVER_SCAN_DESCENDANTS` is set, so several workers can run on one host
/// without each reporting the others' solvers as its own.
pub fn solver_busy() -> bool {
    if worker_scoped_scan() {
        return solver_busy_descendants_only();
    }
    let sys = scan_solver_system();
    sys.processes().values().any(is_live_solver)
}

/// Collect the PIDs of every live (non-zombie) solver process that is
/// a descendant of the current process, given an already-refreshed
/// `System` snapshot. Shared by `solver_busy_descendants_only` and
/// `terminate_solver_descendants_only` so the descendant-tree walk
/// can't drift between the busy check and the kill. The current
/// process (``me``) is never included even if it somehow matched.
fn solver_descendant_pids(sys: &System) -> Vec<sysinfo::Pid> {
    let me = sysinfo::Pid::from_u32(std::process::id());
    let processes = sys.processes();
    // Build a parent->child map so we can walk the descendant tree
    // in a single pass. ``Process::parent`` only gives us one edge,
    // so the loop has to start from ``me`` and follow children.
    let mut children_of: std::collections::HashMap<sysinfo::Pid, Vec<sysinfo::Pid>> =
        std::collections::HashMap::new();
    for (pid, proc) in processes.iter() {
        if let Some(parent) = proc.parent() {
            children_of.entry(parent).or_default().push(*pid);
        }
    }
    let mut matches: Vec<sysinfo::Pid> = Vec::new();
    let mut stack: Vec<sysinfo::Pid> = vec![me];
    let mut seen: std::collections::HashSet<sysinfo::Pid> = std::collections::HashSet::new();
    while let Some(pid) = stack.pop() {
        if !seen.insert(pid) {
            continue;
        }
        if let Some(proc) = processes.get(&pid) {
            if pid != me && is_live_solver(proc) {
                matches.push(pid);
            }
        }
        if let Some(kids) = children_of.get(&pid) {
            stack.extend(kids.iter().copied());
        }
    }
    matches
}

/// True iff any **descendant** of the current process whose name
/// contains `SOLVER_PROCESS_NAME` is running and not a zombie, so a peer
/// worker's solver (running on the same host but in a different process
/// tree) does not trip our own "solver already running" guard.
///
/// LIVE, AND SELECTED AT RUNTIME. [`solver_busy`] calls this whenever
/// `worker_scoped_scan()` reads `PPF_SOLVER_SCAN_DESCENDANTS`, so the selector
/// is a runtime signal rather than a build-time one.
/// The race it answers is a property of running several workers on one host and
/// not of any backend. Re-key [`terminate_solver_descendants_only`] in the same
/// change, never one alone: the kill set and the check set have to agree.
pub fn solver_busy_descendants_only() -> bool {
    let sys = scan_solver_system();
    !solver_descendant_pids(&sys).is_empty()
}

// ---------------------------------------------------------------------------
// Additional utility helpers.

/// Resolve the export base path.
/// In fast-check mode, exports go into the cache; otherwise to the
/// repo-relative `export` directory.
pub fn get_export_base_path(base_dir: &Path) -> String {
    if is_fast_check() {
        get_cache_dir(base_dir)
            .join("export")
            .to_string_lossy()
            .into_owned()
    } else {
        "export".to_string()
    }
}

/// Render a column-oriented mapping to an HTML table. The caller passes
/// (column_name, [cell_string, ...]) pairs in the desired column order.
pub fn dict_to_html_table(columns: &[(String, Vec<String>)], classes: &str) -> String {
    if columns.is_empty() {
        return "<table></table>".to_string();
    }
    let num_rows = columns[0].1.len();
    let mut out = String::new();
    out.push_str(&format!("<table class=\"{classes}\">"));
    out.push_str("<thead><tr>");
    for (col, _) in columns {
        out.push_str(&format!("<th>{col}</th>"));
    }
    out.push_str("</tr></thead>");
    out.push_str("<tbody>");
    for i in 0..num_rows {
        out.push_str("<tr>");
        for (_, vals) in columns {
            let val = if i < vals.len() { vals[i].as_str() } else { "" };
            out.push_str(&format!("<td>{val}</td>"));
        }
        out.push_str("</tr>");
    }
    out.push_str("</tbody>");
    out.push_str("</table>");
    out
}

/// Read the `.CI` marker file from the given frontend directory. Returns
/// `None` if the file is absent. Returns an error if the file exists
/// but is empty.
pub fn ci_name(frontend_dir: &std::path::Path) -> Result<Option<String>, &'static str> {
    let path = frontend_dir.join(".CI");
    if !path.exists() {
        return Ok(None);
    }
    let content = std::fs::read_to_string(&path).map_err(|_| "could not read .CI file")?;
    let last = content.lines().last().unwrap_or("").trim().to_string();
    if last.is_empty() {
        return Err("The .CI file is empty. Please add the name of the CI environment.");
    }
    Ok(Some(last))
}

/// Get the path to the CI root directory: `<cache_dir>/ci`.
pub fn get_ci_root(base_dir: &Path) -> PathBuf {
    get_cache_dir(base_dir).join("ci")
}

/// Get the path to a specific CI's directory: `<cache_dir>/ci/<ci_name>`.
pub fn get_ci_dir(base_dir: &Path, ci_name: &str) -> PathBuf {
    get_ci_root(base_dir).join(ci_name)
}

/// True if a `.CLI` or `.CI` marker file is present. Used as the
/// notebook-detection short-circuit.
pub fn has_cli_or_ci_marker(frontend_dir: &std::path::Path) -> bool {
    frontend_dir.join(".CLI").exists() || frontend_dir.join(".CI").exists()
}

/// Terminate every non-zombie process whose name contains
/// `SOLVER_PROCESS_NAME`. Errors during signaling individual processes
/// are swallowed.
///
/// Platform note: Windows has no POSIX signals, and
/// `Process::kill_with(Signal::Term)` returns `None` on Windows
/// (sysinfo only maps `Signal::Kill` there, to `TerminateProcess`).
/// Without the windows branch the addon's "Terminate" button was a
/// no-op: the server kept reporting BUSY because the solver
/// subprocess was never signaled, and the UI reverted from
/// "Terminating…" back to "Simulating…". On Unix we keep SIGTERM so
/// the solver can flush state; on Windows we fall back to
/// `Process::kill()` (TerminateProcess) since there's no graceful
/// equivalent.
pub fn terminate_solver() {
    // SCOPED THE SAME WAY THE BUSY CHECK IS, and it must be: scoping only the
    // check would leave a worker that correctly ignores a peer's solver still
    // able to KILL it, which is the race `executor/mod.rs` names.
    if worker_scoped_scan() {
        terminate_solver_descendants_only();
        return;
    }
    let sys = scan_solver_system();
    for proc in sys.processes().values().filter(|p| is_live_solver(p)) {
        #[cfg(unix)]
        let _ = proc.kill_with(Signal::Term);
        #[cfg(windows)]
        let _ = proc.kill();
    }
}

/// Terminate only the live (non-zombie) solver processes that are
/// descendants of the current process, so a worker that kills or
/// relaunches its own solver does not signal a peer worker's solver
/// running on the same host (a different process tree). This keeps the
/// kill set aligned with [`solver_busy_descendants_only`]'s check set.
///
/// CURRENTLY UNREFERENCED, for the reason given on that function, and it must
/// be re-keyed together with it: a descendant-only check paired with a
/// host-global kill would SIGTERM every peer worker's solver the moment our
/// own descendant is detected.
///
/// Snapshot the descendant PIDs from a single refresh before signaling
/// any of them: killing mutates the process table, so re-walking after
/// a signal could miss or misattribute PIDs. We also keep the zombie
/// skip (via `is_live_solver`) so we never signal an already-reaped PID
/// and risk hitting a reused PID. Per-platform signaling matches
/// `terminate_solver`.
pub fn terminate_solver_descendants_only() {
    let sys = scan_solver_system();
    let pids = solver_descendant_pids(&sys);
    for pid in pids {
        if let Some(proc) = sys.process(pid) {
            #[cfg(unix)]
            let _ = proc.kill_with(Signal::Term);
            #[cfg(windows)]
            let _ = proc.kill();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generic targets must have been EXPANDED, not copied through.
    ///
    /// The failure this catches is silent and total: if `build.rs` emitted the
    /// manifest's own strings, `SUPPORTED_GFX` would hold `gfx11-generic`, no
    /// device would ever match a name it does not report, and the gate would
    /// refuse every AMD machine while looking perfectly well formed.
    #[test]
    fn supported_gfx_holds_parts_rather_than_families() {
        assert!(!SUPPORTED_GFX.is_empty(), "the manifest expanded to nothing");
        for entry in SUPPORTED_GFX {
            assert!(
                !entry.contains("-generic"),
                "SUPPORTED_GFX holds {entry:?}, which is a family and not a name \
                 any device reports"
            );
        }
        // BOTH WAYS A PART CAN ENTER THE LIST, pinned separately because they
        // are different mechanisms and a change to either is silent.
        //
        // Through a generic target: the toolchain covers gfx115X under
        // gfx11-generic even though AMD ships those as a separate distribution,
        // which is the membership the plan guessed wrong.
        assert!(gfx_is_supported("gfx1151"), "gfx11-generic must cover gfx1151");
        assert!(gfx_is_supported("gfx1100"), "gfx11-generic must cover gfx1100");
        // As a bare part: no generic target covers gfx908 or gfx90a, so they are
        // listed in rocm_arch.txt on their own and cover exactly themselves.
        assert!(gfx_is_supported("gfx908"), "gfx908 is a bare target in the manifest");
        assert!(gfx_is_supported("gfx90a"), "gfx90a is a bare target in the manifest");
        // AND THE EXPANSION IS NOT OVER-BROAD, which is what the two above would
        // stop testing if the table ever grew a family by accident: gfx9-4-generic
        // is gfx942 and gfx950, so its neighbours must not be swept in.
        assert!(
            !gfx_is_supported("gfx940"),
            "gfx940 is in no generic target and no manifest line; claiming it \
             would promise a code object that was never emitted"
        );
        assert!(!gfx_is_supported("gfx941"), "gfx941 is likewise not shipped");
    }

    /// A device names its features after the part, and they are not part of the
    /// question. Matching the whole string would refuse most real machines.
    #[test]
    fn gfx_match_ignores_the_target_id_features() {
        assert!(gfx_is_supported("gfx942:sramecc+:xnack-"));
        assert!(gfx_is_supported("gfx1030:xnack-"));
        assert!(gfx_is_supported("  gfx1200  "), "surrounding space is not a part");
        // Still exact on the part itself: an AMD code object is not forward
        // compatible within a family the way a CUDA cubin is.
        assert!(!gfx_is_supported("gfx1104"));
        assert!(!gfx_is_supported("gfx11"));
        assert!(!gfx_is_supported(""));
    }

    /// The renderer is what a refused user reads, so it must name parts.
    #[test]
    fn supported_gfx_list_names_every_part() {
        let rendered = supported_gfx_list();
        for entry in SUPPORTED_GFX {
            assert!(rendered.contains(entry), "{entry} missing from {rendered:?}");
        }
    }

    #[test]
    fn fast_check_default_is_false() {
        // The flag is process-wide; a parallel test could flip it,
        // so we don't assert the *initial* state, only the
        // round-trip semantics.
        let prior = is_fast_check();
        set_fast_check(true);
        assert!(is_fast_check());
        set_fast_check(false);
        assert!(!is_fast_check());
        // Restore prior state to avoid flakiness when other tests
        // observe the global.
        set_fast_check(prior);
    }

    #[test]
    fn cache_dir_returns_directory() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = get_cache_dir(tmp.path());
        assert!(dir.exists() || dir.parent().map(|p| p.exists()).unwrap_or(false));
    }

    #[test]
    fn cache_dir_of_a_packaged_tree_stays_inside_it() {
        // The same statement `datamodel::app` makes, asked of THIS resolver,
        // because the two must agree for a packaged tree, and export, CI and
        // render-temp all come through here.
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path()
                .join(crate::datamodel::app::SELFCONTAINED_MARKER),
            "",
        )
        .unwrap();
        let dir = get_cache_dir(tmp.path());
        assert!(
            dir.starts_with(tmp.path()),
            "a packaged tree cached outside itself: {dir:?}"
        );
    }

    #[test]
    fn solver_busy_returns_bool() {
        // No solver running in a test context; the call must
        // complete without error and produce a bool.
        let _busy = solver_busy();
    }

    #[test]
    fn terminate_solver_descendants_only_runs_to_completion() {
        // No solver descendant in a test context; the terminator must
        // complete without error and signal nothing.
        terminate_solver_descendants_only();
    }

    /// Clone `sleep` into a temp dir under a name that contains
    /// SOLVER_PROCESS_NAME. Detection keys off `Process::name`, which on
    /// Linux is the executable's ``comm`` (its basename), so renaming the
    /// binary, not just argv[0], is what makes the clone look like the
    /// real ``ppf-contact-solver``. Returns the temp dir (the caller must
    /// keep it alive while the process runs) and the binary path, or None
    /// when the host has no `sleep` to clone.
    #[cfg(unix)]
    fn clone_solver_named_sleep() -> Option<(tempfile::TempDir, std::path::PathBuf)> {
        use std::os::unix::fs::PermissionsExt;
        let sleep_bin = ["/bin/sleep", "/usr/bin/sleep"]
            .iter()
            .map(std::path::PathBuf::from)
            .find(|p| p.exists())?;
        let dir = tempfile::tempdir().ok()?;
        let bin = dir.path().join("ppf-contact-sibling");
        std::fs::copy(&sleep_bin, &bin).ok()?;
        std::fs::set_permissions(&bin, std::fs::Permissions::from_mode(0o755)).ok()?;
        Some((dir, bin))
    }

    /// POSIX ``kill -0``: true iff a process with `pid` exists. Routed
    /// through the shell so it works on hosts without a standalone
    /// ``/bin/kill`` and on both Linux and macOS.
    #[cfg(unix)]
    fn pid_alive(pid: i32) -> bool {
        std::process::Command::new("sh")
            .arg("-c")
            .arg(format!("kill -0 {pid}"))
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    }

    #[cfg(unix)]
    #[test]
    fn descendant_terminator_spares_non_descendant_solver() {
        use std::process::Command;

        // A solver-named binary running OUTSIDE our descendant tree must
        // be spared. Build the clone, launch it in the background from a
        // short-lived launcher shell, and let the launcher exit so the
        // process is orphaned (reparented to init) and no longer a
        // descendant of this test process. The launcher (not the orphan)
        // is what ``status()`` reaps, so we capture the orphan's PID via
        // a file.
        let (dir, bin) = match clone_solver_named_sleep() {
            Some(pair) => pair,
            None => return,
        };
        let pidfile = dir.path().join("pid");
        let script = format!(
            "'{bin}' 30 & echo $! > '{pid}'",
            bin = bin.display(),
            pid = pidfile.display(),
        );
        if Command::new("sh").arg("-c").arg(&script).status().is_err() {
            return;
        }
        // Let the orphan be reparented and appear in the process table.
        std::thread::sleep(std::time::Duration::from_millis(200));
        let pid = match std::fs::read_to_string(&pidfile)
            .ok()
            .and_then(|s| s.trim().parse::<i32>().ok())
        {
            Some(p) => p,
            None => return,
        };

        // Skip (rather than falsely fail) if we couldn't establish a
        // live sibling, or if this environment did not actually detach it
        // from our descendant tree (e.g. a sandbox with an unusual
        // reaper). We check the precondition with the same descendant
        // walk the terminator uses.
        if !pid_alive(pid) {
            return;
        }
        let sys = scan_solver_system();
        if solver_descendant_pids(&sys).contains(&sysinfo::Pid::from_u32(pid as u32)) {
            let _ = Command::new("sh").arg("-c").arg(format!("kill -9 {pid}")).status();
            return;
        }

        terminate_solver_descendants_only();

        // Allow any (erroneous) signal to land before checking.
        std::thread::sleep(std::time::Duration::from_millis(150));
        let still_alive = pid_alive(pid);
        let _ = Command::new("sh").arg("-c").arg(format!("kill -9 {pid}")).status();

        assert!(
            still_alive,
            "descendant-only terminator must not signal a non-descendant solver-named sibling"
        );
    }

    #[cfg(unix)]
    #[test]
    fn descendant_terminator_kills_descendant_solver() {
        use std::process::{Command, Stdio};

        // A solver-named DIRECT CHILD of this test process is inside our
        // descendant tree, so the terminator must signal it.
        let (_dir, bin) = match clone_solver_named_sleep() {
            Some(pair) => pair,
            None => return,
        };
        let mut child = match Command::new(&bin)
            .arg("30")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
        {
            Ok(c) => c,
            Err(_) => return,
        };
        std::thread::sleep(std::time::Duration::from_millis(200));
        // Sanity: the child must be running (and seen as a descendant)
        // before we exercise the kill, else the assertion is vacuous.
        let sys = scan_solver_system();
        let is_descendant =
            solver_descendant_pids(&sys).contains(&sysinfo::Pid::from_u32(child.id()));
        if !matches!(child.try_wait(), Ok(None)) || !is_descendant {
            let _ = child.kill();
            let _ = child.wait();
            return;
        }

        terminate_solver_descendants_only();

        // SIGTERM should reach the child; poll briefly for its exit.
        let mut exited = false;
        for _ in 0..50 {
            if matches!(child.try_wait(), Ok(Some(_))) {
                exited = true;
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
        let _ = child.kill();
        let _ = child.wait();

        assert!(
            exited,
            "descendant-only terminator must signal a descendant solver-named child"
        );
    }

    #[test]
    fn check_gpu_runs_to_completion() {
        // We don't assume a GPU (NVIDIA, AMD or Apple) is present on every
        // host this runs on; the function must produce *some* Result
        // without panicking, on the CUDA arm (non-macOS), the Metal arm
        // (macOS) or the ROCm arm
        // (`--features rocm`, Linux and Windows). Either Ok(()) (a runner with
        // a matching real GPU) or a typed error.
        //
        // UNDER `--features rocm` THIS IS THE PROBE'S LINK TEST, and it is the
        // only one: the arm calls a C function this crate's build script
        // compiled against the SDK's headers, so a wrong extern signature, a
        // missing `amdhip64` or a probe that traps on a machine with no AMD
        // device all surface here rather than in front of a user.
        // PRINTED RATHER THAN DISCARDED, because the verdict is the only thing
        // this test can report and `cargo test -- --nocapture` is how a host's
        // arm is read back. It is not asserted: which verdict is correct
        // depends on the machine.
        println!("check_gpu() on this host: {:?}", check_gpu());
    }

    #[test]
    fn visible_device_position_defaults_only_on_a_single_gpu() {
        let one = [(0u32, "GPU-aaaa")];
        let two = [(0u32, "GPU-aaaa"), (1, "GPU-bbbb")];
        assert_eq!(visible_device_position(&one, None), Some(0));
        assert_eq!(visible_device_position(&two, None), None);
        assert_eq!(visible_device_position(&[], None), None);
    }

    #[test]
    fn visible_device_position_honors_an_empty_mask() {
        let rows = [(0u32, "GPU-aaaa"), (1, "GPU-bbbb")];
        assert_eq!(visible_device_position(&rows, Some("")), None);
        assert_eq!(visible_device_position(&rows, Some("  ")), None);
    }

    #[test]
    fn visible_device_position_reads_the_first_entry() {
        let rows = [(0u32, "GPU-aaaa"), (1, "GPU-bbbb"), (2, "GPU-cccc")];
        assert_eq!(visible_device_position(&rows, Some("2")), None);
        assert_eq!(visible_device_position(&rows, Some("2,0")), None);
        assert_eq!(visible_device_position(&rows, Some(" 1 , 2 ")), None);
        assert_eq!(
            visible_device_position(&rows, Some("GPU-cccc")),
            Some(2)
        );
    }

    #[test]
    fn visible_device_position_accepts_a_uuid_prefix() {
        let rows = [(0u32, "GPU-aaaa1111"), (1, "GPU-bbbb2222")];
        assert_eq!(
            visible_device_position(&rows, Some("GPU-bbbb2222")),
            Some(1)
        );
        assert_eq!(visible_device_position(&rows, Some("GPU-bbbb")), Some(1));
    }

    #[test]
    fn visible_device_position_rejects_an_ambiguous_uuid_prefix() {
        let rows = [(0u32, "GPU-aaaa1111"), (1, "GPU-aaaa2222")];
        assert_eq!(visible_device_position(&rows, Some("GPU-aaaa")), None);
    }

    #[test]
    fn visible_device_position_rejects_an_absent_device() {
        let rows = [(0u32, "GPU-aaaa"), (1, "GPU-bbbb")];
        assert_eq!(visible_device_position(&rows, Some("7")), None);
        assert_eq!(visible_device_position(&rows, Some("GPU-zzzz")), None);
    }

    #[test]
    fn parse_gpu_rows_keeps_a_comma_in_the_name() {
        let out = "0, GPU-aaaa, 46068, 8.9, NVIDIA L40S\n\
                   1, GPU-bbbb, 16376, 8.9, NVIDIA RTX A4000, Inc.\n";
        let rows = parse_gpu_rows(out, 2);
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].index, 0);
        assert_eq!(rows[0].uuid, "GPU-aaaa");
        assert_eq!(rows[0].fields, vec!["46068", "8.9"]);
        assert_eq!(rows[0].name, "NVIDIA L40S");
        assert_eq!(rows[1].name, "NVIDIA RTX A4000, Inc.");
    }

    #[test]
    fn parse_gpu_rows_drops_an_unreadable_row() {
        let out = "\n\
                   not-a-row\n\
                   x, GPU-aaaa, 8.9, NVIDIA L40S\n\
                   0, GPU-bbbb, 8.9, NVIDIA L40S\n";
        let rows = parse_gpu_rows(out, 1);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].uuid, "GPU-bbbb");
    }

    #[test]
    fn dict_to_html_table_empty() {
        let out = dict_to_html_table(&[], "table");
        assert_eq!(out, "<table></table>");
    }

    #[test]
    fn dict_to_html_table_basic() {
        let cols = vec![
            ("name".to_string(), vec!["a".to_string(), "b".to_string()]),
            ("value".to_string(), vec!["1".to_string(), "2".to_string()]),
        ];
        let out = dict_to_html_table(&cols, "tbl");
        assert!(out.contains("<table class=\"tbl\">"));
        assert!(out.contains("<th>name</th>"));
        assert!(out.contains("<th>value</th>"));
        assert!(out.contains("<td>a</td>"));
        assert!(out.contains("<td>2</td>"));
    }

    #[test]
    fn ci_name_missing_returns_none() {
        let tmp = tempfile::tempdir().unwrap();
        let r = ci_name(tmp.path()).unwrap();
        assert!(r.is_none());
    }

    #[test]
    fn ci_name_present_returns_last_line() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join(".CI"), "first\ngithub-actions\n").unwrap();
        let r = ci_name(tmp.path()).unwrap();
        assert_eq!(r.as_deref(), Some("github-actions"));
    }

    #[test]
    fn ci_name_empty_errors() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join(".CI"), "").unwrap();
        let r = ci_name(tmp.path());
        assert!(r.is_err());
    }

    #[test]
    fn get_ci_root_under_cache() {
        let tmp = tempfile::tempdir().unwrap();
        let r = get_ci_root(tmp.path());
        assert!(r.ends_with("ci"));
    }

    #[test]
    fn get_export_base_path_respects_fast_check() {
        let tmp = tempfile::tempdir().unwrap();
        let prior = is_fast_check();
        set_fast_check(true);
        let p = get_export_base_path(tmp.path());
        assert!(p.contains("export"));
        set_fast_check(false);
        assert_eq!(get_export_base_path(tmp.path()), "export");
        set_fast_check(prior);
    }

    #[test]
    fn check_gpu_error_messages_match_python() {
        // Lock the user-visible error strings byte-for-byte against
        // what the Python source emits (the addon's error UI has
        // copy that triggers off these exact substrings).
        let m = format!("{}", GpuError::NvidiaSmiMissing);
        assert!(m.contains("nvidia-smi not found"));
        assert!(m.contains("NVIDIA GPU"));

        let f = format!("{}", GpuError::NvidiaSmiFailed);
        assert!(f.contains("nvidia-smi failed"));

        let un = format!(
            "{}",
            GpuError::SmUnsupported {
                name: "GeForce GTX 980".into(),
                actual: 52,
                supported: supported_sm_list(),
            }
        );
        assert!(un.contains("GeForce GTX 980"));
        assert!(un.contains("sm_52")); // the detected, unsupported arch
        assert!(un.contains("sm_86")); // the supported set is spelled out
        assert!(un.contains("sm_120"));
    }

    #[test]
    fn check_gpu_metal_error_messages_are_actionable() {
        // Same spirit as check_gpu_error_messages_match_python above, but
        // for the Metal arm's error variants. These variants are not behind a
        // `#[cfg(target_os = "macos")]` gate, so this test (and its
        // messages) is exercised on every CI host, not only macOS.
        let missing = format!("{}", GpuError::MetalDeviceMissing);
        assert!(missing.contains("MTLCreateSystemDefaultDevice"));
        assert!(missing.contains("No Metal-capable GPU"));
        // NO SILENT FALLBACK IS EVER IMPLIED BY THIS MESSAGE: it names the
        // failure and stops there. Both spellings are refused, because the
        // rule is about what the message may promise and not about one word.
        assert!(!missing.to_lowercase().contains("emulat"));
        assert!(!missing.to_lowercase().contains("fall back"));

        let unsupported = format!(
            "{}",
            GpuError::MetalFamilyUnsupported {
                name: "AMD Radeon Pro 5500M".into(),
                required: METAL_MIN_FAMILY_DESC.to_string(),
            }
        );
        assert!(unsupported.contains("AMD Radeon Pro 5500M"));
        assert!(unsupported.contains("Apple7"));
        assert!(unsupported.contains("Apple Silicon"));
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn check_gpu_macos_routes_to_metal_arm() {
        // On macOS, check_gpu() must never reach for nvidia-smi: any
        // error it returns has to be one of the Metal-arm variants, not
        // a CUDA one. A CUDA-shaped error here would mean the platform
        // dispatch in check_gpu() regressed and macOS is silently
        // falling through to the nvidia-smi path.
        match check_gpu() {
            Ok(()) => {}
            Err(GpuError::MetalDeviceMissing | GpuError::MetalFamilyUnsupported { .. }) => {}
            Err(other) => panic!("check_gpu() on macOS returned a non-Metal error: {other}"),
        }
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn check_gpu_non_macos_routes_to_cuda_arm() {
        // Mirror of the macOS test above: off macOS, check_gpu() must
        // stay on the nvidia-smi path and never return a Metal-arm
        // error, which would only be reachable if the dispatch in
        // check_gpu() started compiling the Metal arm for this target.
        // The assertion names the two Metal variants rather than the CUDA
        // ones because the property under test is "no Metal-arm error":
        // enumerating the CUDA arm's variants instead would fail this
        // test on a perfectly healthy host every time a CUDA-arm variant
        // is added (as CUDA_VISIBLE_DEVICES validation added two).
        if let Err(err) = check_gpu() {
            assert!(
                !matches!(
                    err,
                    GpuError::MetalDeviceMissing | GpuError::MetalFamilyUnsupported { .. }
                ),
                "check_gpu() off macOS returned a Metal-arm error: {err}"
            );
        }
    }

    #[test]
    fn sm_coverage_uses_minor_compat_within_major() {
        // A shipped cubin covers its own arch and higher minors in the same
        // major (SASS forward minor-compat), but never a different major or a
        // lower minor.
        assert!(sm_is_supported(61)); // Pascal (GTX 10, Titan Xp)
        assert!(sm_is_supported(62)); // Pascal minor bump: sm_61 cubin, 1 <= 2
        assert!(sm_is_supported(75)); // Turing (RTX 20, GTX 16, T4)
        assert!(sm_is_supported(86)); // Ampere (RTX 30, A40)
        assert!(sm_is_supported(87)); // Jetson Orin: sm_86 cubin, 6 <= 7
        assert!(sm_is_supported(89)); // Ada (RTX 40, L40S)
        assert!(sm_is_supported(90)); // Hopper (H100)
        assert!(sm_is_supported(100)); // Blackwell datacenter (B200)
        assert!(sm_is_supported(120)); // Blackwell consumer (RTX 50-series)
        assert!(sm_is_supported(121)); // hypothetical Blackwell minor bump

        assert!(!sm_is_supported(80)); // A100: same major but minor 0 < 6
        assert!(!sm_is_supported(60)); // Tesla P100: Pascal major, minor 0 < 1
        assert!(!sm_is_supported(52)); // Maxwell (GTX 900): no cubin shipped
        assert!(!sm_is_supported(130)); // future major, no cubin shipped yet
    }
}
