# File: jupyter_ops.py
# Code: Claude Code and Codex
# Review: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

import copy
import json
import webbrowser

import bpy  # pyright: ignore

from bpy.types import Operator  # pyright: ignore

from ..core.client import communicator as com
from ..core.protocol import HEADER_JSON_DATA
from ..core.utils import redraw_all_areas
from ..models.groups import get_addon_data


JUPYTER_NOTEBOOK_TEMPLATE = {
    "cells": [
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "7ecae1ae-f594-4f38-be03-3a8b696c5382",
            "metadata": {},
            "outputs": [],
            "source": [
                "# File: {project_name}.ipynb\n",
                "# Code: Auto-generated by ZOZO's Contact Solver Blender Add-on",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "45c24c22-c6e9-437a-b2ba-e75b9b58e597",
            "metadata": {},
            "outputs": [],
            "source": [
                "from frontend import BlenderApp\n",
                "\n",
                "# Attach to whatever state the Blender addon has produced.\n",
                "# Recovers a built scene if available; otherwise populates + builds\n",
                "# from the uploaded data.pickle / param.pickle.\n",
                'app = BlenderApp.open("{project_name}")\n',
                "\n",
                "# Report and preview the scene. Safe to re-run.\n",
                "app.scene.report()\n",
                "app.scene.preview()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "d2f1cdd9-19f0-4d89-9ee5-74a1bc4134d8",
            "metadata": {},
            "outputs": [],
            "source": [
                "# Launch the solver (or attach to a running one, e.g. if the\n",
                "# Blender addon started it). To pick up a saved state instead,\n",
                "# call app.session.resume() explicitly.\n",
                "app.session.run()\n",
                "\n",
                "# Live frame playback + realtime stdout.\n",
                "app.session.preview()\n",
                "app.session.stream()",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.3",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}


class JUPYTER_OT_Export(Operator):
    """Export a JupyterLab notebook via the solver server."""

    bl_idname = "solver.jupyter_export"
    bl_label = "Export"

    filepath: bpy.props.StringProperty(  # pyright: ignore
        name="Path",
        description="Notebook path relative to JupyterLab root",
        default="",
    )

    @classmethod
    def poll(cls, context):
        return com.is_connected()

    def invoke(self, context, event):
        state = get_addon_data(context.scene).state
        last = state.jupyter_last_export.strip()
        if last:
            self.filepath = last
        else:
            name = state.project_name.strip() or "unnamed"
            self.filepath = f"blender-export/{name}.ipynb"
        return context.window_manager.invoke_props_dialog(self)

    def draw(self, context):
        self.layout.prop(self, "filepath")

    def execute(self, context):
        filepath = self.filepath.strip()
        if not filepath:
            self.report({"ERROR"}, "Filepath is empty")
            return {"CANCELLED"}
        if not filepath.endswith(".ipynb"):
            self.report({"ERROR"}, "Filename must end with .ipynb")
            return {"CANCELLED"}

        state = get_addon_data(context.scene).state
        project_name = filepath.rsplit("/", 1)[-1].removesuffix(".ipynb")

        notebook = copy.deepcopy(JUPYTER_NOTEBOOK_TEMPLATE)
        for cell in notebook["cells"]:
            cell["source"] = [
                line.replace("{project_name}", project_name)
                for line in cell["source"]
            ]
        payload = json.dumps(notebook).encode("utf-8")

        # Route the write through the solver server instead of JupyterLab's
        # contents API. Hitting /api/contents was making the exported file
        # (and its parent `blender-export/` dir) vanish after a while —
        # suspected interaction with JupyterLab's cloned-workspace state.
        # server.py resolves relative_path against <src>/examples/.
        connection = com.connection
        if not connection.instance or not com.is_connected():
            self.report({"ERROR"}, "Not connected to solver server. Connect first.")
            return {"CANCELLED"}

        channel = None
        try:
            channel = connection.instance.open_channel()
            channel.sendall(HEADER_JSON_DATA)
            header = json.dumps({
                "request": "notebook_send",
                "relative_path": filepath,
                "size": len(payload),
                "name": project_name,
            }).encode() + b"\n"
            channel.sendall(header)
            channel.sendall(payload)
            response = b""
            while b"\n" not in response:
                chunk = channel.recv(1024)
                if not chunk:
                    break
                response += chunk
            if b"OK" not in response:
                try:
                    err = json.loads(response.decode().strip()).get("error", response.decode().strip())
                except Exception:
                    err = response.decode(errors="replace").strip() or "no response"
                self.report({"ERROR"}, f"Server rejected notebook: {err}")
                return {"CANCELLED"}
        except Exception as e:
            self.report({"ERROR"}, f"Export failed: {e}")
            return {"CANCELLED"}
        finally:
            if channel is not None:
                try:
                    channel.close()
                except Exception:
                    pass

        state.jupyter_last_export = filepath
        self.report({"INFO"}, f"Exported {filepath} via solver server")
        redraw_all_areas(context)
        return {"FINISHED"}


class JUPYTER_OT_OpenURL(Operator):
    """Open the JupyterLab notebook in a browser."""

    bl_idname = "solver.jupyter_open"
    bl_label = "Open URL"

    @classmethod
    def poll(cls, context):
        return bool(get_addon_data(context.scene).state.jupyter_last_export.strip())

    def execute(self, context):
        state = get_addon_data(context.scene).state
        port = state.jupyter_port
        path = state.jupyter_last_export.strip()
        url = f"http://localhost:{port}/lab/tree/{path}"
        webbrowser.open(url)
        self.report({"INFO"}, f"Opened {url}")
        return {"FINISHED"}


class JUPYTER_OT_Delete(Operator):
    """Delete the exported notebook via the solver server."""

    bl_idname = "solver.jupyter_delete"
    bl_label = "Delete"

    @classmethod
    def poll(cls, context):
        state = get_addon_data(context.scene).state
        return com.is_connected() and bool(state.jupyter_last_export.strip())

    def execute(self, context):
        state = get_addon_data(context.scene).state
        filepath = state.jupyter_last_export.strip()
        project_name = filepath.rsplit("/", 1)[-1].removesuffix(".ipynb")

        connection = com.connection
        if not connection.instance or not com.is_connected():
            self.report({"ERROR"}, "Not connected to solver server. Connect first.")
            return {"CANCELLED"}

        channel = None
        try:
            channel = connection.instance.open_channel()
            channel.sendall(HEADER_JSON_DATA)
            header = json.dumps({
                "request": "notebook_delete",
                "relative_path": filepath,
                "name": project_name,
            }).encode() + b"\n"
            channel.sendall(header)
            response = b""
            while b"\n" not in response:
                chunk = channel.recv(1024)
                if not chunk:
                    break
                response += chunk
            if b"OK" not in response:
                try:
                    err = json.loads(response.decode().strip()).get("error", response.decode().strip())
                except Exception:
                    err = response.decode(errors="replace").strip() or "no response"
                self.report({"ERROR"}, f"Server rejected delete: {err}")
                return {"CANCELLED"}
        except Exception as e:
            self.report({"ERROR"}, f"Delete failed: {e}")
            return {"CANCELLED"}
        finally:
            if channel is not None:
                try:
                    channel.close()
                except Exception:
                    pass

        state.jupyter_last_export = ""
        self.report({"INFO"}, f"Deleted {filepath}")
        redraw_all_areas(context)
        return {"FINISHED"}


classes = (
    JUPYTER_OT_Export,
    JUPYTER_OT_OpenURL,
    JUPYTER_OT_Delete,
)


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
